### ISSUE TITLE
脚本位置问题

### ISSUE THREAD

**Issue by yanhuacuo** [hchunhui/librime-lua#10]
现在的 librime 对 rime.lua 的读取，限制在「用户文件夹」下面。
如果在「程序文件夹」的「data」位置上，就不会生效。
「data」是程序的「yaml」文件目录。
win之外，mac 、linux 也都尝试过，一样限制在「用户文件夹」下面。
是否可以放宽 librime 对 rime.lua 读取位置的限制？
或者，如果我想改一改，应该做哪些事情？
求指点。

**Comment by hchunhui** [comment]
是通过下面这一行的值来控制的。
https://github.com/hchunhui/librime-lua/blob/bb6fca18b22ceee46fa0f78b0c4866f488872ac4/src/modules.cc#L10

我不确定是否是改成 `RimeGetSharedDataDir()` 就能从 `data` 读取，可以试试。

**Comment by yanhuacuo** [comment]
> 是通过下面这一行的值来控制的。
> https://github.com/hchunhui/librime-lua/blob/bb6fca18b22ceee46fa0f78b0c4866f488872ac4/src/modules.cc#L10
> 
> 我不确定是否是改成 `RimeGetSharedDataDir()` 就能从 `data` 读取，可以试试。

确认有效，非常感谢，这样我们在打包时就不用去研究不同平台下的安装脚本了。

**Comment by yanhuacuo** [comment]
谢谢，分享 rime.dll :
https://github.com/yanhuacuo/librime-lua

**Comment by yanhuacuo** [comment]
作者您好，注意到 types.cc 下也有关于文件位置的指定，如上改为 RimeGetSharedDataDir 后，脚本调用上仍然有问题。
非脚本及操作方面的问题，一月份时编译的版本现在依然工作正常。因为 MacOS 下编译打包放在 app 目录下比较方便，所以有将脚本预置到程序目录下的需求，请求帮助。

https://github.com/hchunhui/librime-lua/blob/fb172327f7f0fdb95f559567637520cb5ae9e1b3/src/types.cc#L235
