### ISSUE TITLE
請問如何獲取候選詞？

### ISSUE THREAD

**Issue by JACKCHAN000** [hchunhui/librime-lua#103]
如題
最近看到了rime百度雲輸入方案https://github.com/hchunhui/librime-cloud
想做一個google的翻譯器，把第一個候選詞翻譯成英文後加到候選字列表。
已經做了一個demo，可以輸出翻譯https://github.com/JACKCHAN000/Lua-Google-Translate/blob/main/translator.lua
但在rime lua插件下不能實現，不能輸出任何東西。
請問如何獲取候選詞呢？
希望大神能幫忙實現。
```
local json = require("json")
local http = require("socket.http")
local url = require("socket.url")

local function make_url(input)
   local sl = "zh_TW"
   local tl = "en"
   return 'http://translate.googleapis.com/translate_a/single?client=gtx&sl='.. sl ..'&tl='.. tl ..'&dt=t&q='.. url.escape(input)
end

local function translator(input, seg)
   --get the first Candidate
   for cand in input:iter() do
      Cand1 = cand
      break
   end

   local reply = http.request(make_url(Cand1))
   local data = json.decode(reply)

   for i, v in ipairs(data) do
      -- get the output string
      local output = v[1][1]
      local c = Candidate("translate", seg.start, seg._end, output, "翻譯")
      -- add to Candidate
      yield(c)
   end
end

return translator
```

**Comment by JACKCHAN000** [comment]
英譯中已經成功
https 改成 http 就可以了
```
local json = require("json")
local http = require("socket.http")
local url = require("socket.url")

local function make_url(input)
   local sl = "en"
   local tl = "zh_TW"
   return 'http://translate.googleapis.com/translate_a/single?client=gtx&sl='.. sl ..'&tl='.. tl ..'&dt=t&q='.. url.escape(input)
end

local function translator(input, seg)
   local reply = http.request(make_url(input))
   local data = json.decode(reply)

   for i, v in ipairs(data) do
      -- get the output string
      local output = v[1][1]
      local c = Candidate("translate", seg.start, seg._end, output, "翻譯")
      -- add to Candidate
      yield(c)
   end
end

return translator
```

**Comment by JACKCHAN000** [comment]
只差一個問題
如何獲取第一個的候選詞呢？

**Comment by OnchiuLee** [comment]
> 只差一個問題
> 
> 如何獲取第一個的候選詞呢？

local engine = env.engine
local context = engine.context

local focus_text = context:get_commit_text()

**Comment by OnchiuLee** [comment]
> > > 只差一個問題
> 
> > > 如何獲取第一個的候選詞呢？
> 
> > 
> 
> > local engine = env.engine
> 
> > local context = engine.context
> 
> > 
> 
> > local focus_text = context:get_commit_text()
> 
> 
> 
> 用了之後還是只輸出輸入的英文字，而不是候選詞。

這個在processor中是當前候選項 在filter中可能不是

**Comment by OnchiuLee** [comment]
> > > 只差一個問題
> 
> > > 如何獲取第一個的候選詞呢？
> 
> > 
> 
> > local engine = env.engine
> 
> > local context = engine.context
> 
> > 
> 
> > local focus_text = context:get_commit_text()
> 
> 
> 
> 用了之後還是只輸出輸入的英文字，而不是候選詞。

translator中 
for cand in input:iter() do
    cand.text是遍歷後的每個候選項，你可以針對每個候選進行翻譯操作，在線翻譯可能效率不高 影響體驗
end

**Comment by shewer** [comment]
如果只用 io.popen( "strat  url .....")  直接打開  WEB  ，而不要在回丟到 candidate
利用 ezay-en   split  英文單字  --> url -->web 

可以用 curl  嗎    ???   windows  要require 外部lib 不好處理

那個 url 可以回傳 json 格式嗎??

**Comment by shewer** [comment]
那個程式是  filter 吧 ，  
方法  用 lua_translator   處理  url  也可以  
用 filter  檢查 cand      再處理 url  也可以

1  用 ezay-en  translator    'ilovelua'  -- >   cand.text= "i love lua' 
     yield 

2  filter   if  cand.type== 'translate'    -- > cand.comment= url()


1  用ezay-en  translator   'ilovelua'  -->can.text= 'i love lua'   cand.comment=url()
     yield(cand)

**Comment by JACKCHAN000** [comment]
用for cand in input:iter() do的話會沒有任何輸出
查看日誌出現```E0401 12:45:36.943403 11768 lua_gears.cc:15] LuaTranslation::Next error(2): C:\Users\XXX\AppData\Roaming\Rime\lua\google.lua:14: attempt to call a nil value (method 'iter')
I0401 12:45:36.944399 11768 engine.cc:206] Oops, got a futile translation.```


用context:get_commit_text() 的話只輸出英文輸入，沒有輸出候選字
查看日誌會出現```I0401 13:28:59.431475  4272 engine.cc:206] Oops, got a futile translation.```

用rime輸入法進行翻譯比打開網頁更快
英譯中的版本已經成功，運作效率好像也不錯。
只差中譯英的版本。。。

![final_60642e5be0b45900cf1d6b74_428833](https://user-images.githubusercontent.com/61930699/113112491-cc1b5080-923b-11eb-8599-4a1006c55efe.gif)

**Comment by shewer** [comment]
我用 你的 url  無法 連結 ， error :   沒有權限   API 要錢吧 
translator`input --> string    不能用 iter()



filter          input --> Segment    input:iter()  調出  cand 
```lua
function  lua_translator(input,seg,env)  -- string, Segmention  , env
               if input=="ilovelua" then 
                     yield(  Candidate(  ..... "我愛月亮" ...))
                     yield(   Candidate( .....  "i love lua" ...))
                end 
end 

function lua_filter(  input , env) -- Segment,env   <-- 範例 input  命名不好
               for  cand in  input:iter() 
                     if  cand.type=="Translate" then 
                             cand.commit=  google()
                     end 
                     yield(cand)
               end
         end
end        
```

**Comment by JACKCHAN000** [comment]
> 我用 你的 url 無法 連結 ， error : 沒有權限 API 要錢吧
> translator`input --> string 不能用 iter()
> 
> filter input --> Segment input:iter() 調出 cand
> 
> ```lua
> function  lua_translator(input,seg,env)  -- string, Segmt  , env
>                if input=="ilovelua" then 
>                      yield(  Candidate(  ..... "我愛月亮" ...))
>                      yield(   Candidate( .....  "i love lua" ...))
>                 end 
> end 
> 
> function lua_filter(  input , env) -- Segment,env   <-- 範例 input  命名不好
>                for  cand in  input:iter() 
>                      if  cand.type=="Translate" then 
>                              cand.commit=  google()
>                      end 
>                      yield(cand)
>                end
>          end
> end        
> ```

能用啊
http://translate.googleapis.com/translate_a/single?client=gtx&sl=zh_TW&tl=en&dt=t&q=%e4%bb%8a%e5%a4%a9%e5%a4%a9%e6%b0%a3%e5%be%88%e5%a5%bd
返回```[[["The weather today is good","今天天氣很好",null,null,1]
]
,null,"zh-TW",null,null,null,null,[]
]```

加載lua_filter時不知道為甚麼會彈出

```E0401 17:08:37.734895  4108 lua_gears.cc:15] LuaTranslation::Next error(2): [string "return function (f, ...)..."]:3: attempt to call a nil value (upvalue 'f')```

**Comment by shewer** [comment]
---schema
lua_component@tagname

rime.lua
一般  一檔 一tabel
tagname= require( 'module')
tagname= {init=func , fini=func ,func=func} 

一檔    4 table  模板
https://github.com/shewer/librime-lua-tools/blob/main/template.lua
local init_func=require( template)
init_fun()  
    return { 
            translator = { init=func, fini=func, func=func } ,
            segmentor = ....
            translator = ...
             filter = ....
     }
-------------------------------
rime.lua
------------------------

tagname=  require( module)().filter

**Comment by JACKCHAN000** [comment]
中譯英和英譯中的google翻譯都成功實現了，有興趣試用的話可以到https://github.com/JACKCHAN000/Rime-Lua-GoogleTranslate

中譯英:

![final_606b23cc785d7e003d750948_420746](https://user-images.githubusercontent.com/61930699/113588017-3419ce80-9662-11eb-8ce6-51e6443a32e8.gif)

英譯中:

![final_606b23148efa0600b740d680_363311](https://user-images.githubusercontent.com/61930699/113589246-b8b91c80-9663-11eb-8458-2312e69cfd92.gif)
