### ISSUE TITLE
lua_filter 如何修改 cand.text？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#11]
修改 cand.comment 的方法

```lua
    cand:get_genuine().comment = foo
```

用在 cand.text 上不正常，只有标点符号起作用了。

**Comment by hchunhui** [comment]
修改 `text` 做不到，因为这个属性是只读的（只有 `SimpleCandidate` 除外）。这是 librime 核心库的限制。

要达到修改的效果，只能在 filter 中重建一个新的 `Candidate` 。
但 lua 现在只支持建 `SimpleCandidate`，所以这么干可能会使该项的调频、组词等功能失效。

**Comment by Ace-Who** [comment]
谢谢，明白了。
