### ISSUE TITLE
请问 lua脚本有没有办法读写本地文件

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#116]
我想在本地文件中存储历史数据（比如调用脚本的快捷键名称和时间）

**Comment by shewer** [comment]
https://github.com/hchunhui/librime-lua/blob/15bd231e46fb5c0c7dd8a81d2d30fee9a838f0fa/src/types.cc#L1531
```lua
path=rime_api.get_shared_data_dir  -- windows sharedata   USERDIR/AppData/Roaming/Rime
pathch=package.config:sub(1,1)  -- get "/"  or  "\\"
fn= io.open(path .. pathch .. "backck.txt","r+")
fn:write("------------") 
fn:close()


```

**Comment by hxse** [comment]
请问这个代码是跨平台的吗，还是只适合windows？

**Comment by shewer** [comment]
是的差別在  / \
pathch=package.config:sub(1,1)  -- get "/"  or  "\\"
windows    "\\"
linux   osx   "/"
