### ISSUE TITLE
如何在filter中获得键入编码

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#120]
或者是在translator中获得候选项？

**Comment by OnchiuLee** [comment]
processor里可以

**Comment by OnchiuLee** [comment]
local context = env.engine.context

local composition = context.composition
		local segment = composition:back()
		local candidate_count = segment.menu:candidate_count()  -- 候选项数量

local selected_candidate=segment:get_selected_candidate() -- 焦点项

local cand=segment:get_candidate_at(index).text  -- 获取指定项 从0起

或者 for cand in input:iter() do遍历 cand.text 是选项词

**Comment by hxse** [comment]
在filter中获取键入编码能实现吗

**Comment by shewer** [comment]
> local context = env.engine.context
> 
> local composition = context.composition
> local segment = composition:back()
> local candidate_count = segment.menu:candidate_count() -- 候选项数量
> 
> local selected_candidate=segment:get_selected_candidate() -- 焦点项
> 
> local cand=segment:get_candidate_at(index).text -- 获取指定项 从0起
> 
> 或者 for cand in input:iter() do遍历 cand.text 是选项词

在 translator & filter  可以不用   composition:back()
https://github.com/rime/librime/blob/0ee64d4541b66f7b9397094cdd45260bfb4ac00c/src/rime/engine.cc#L143

把 segments  調出所有  segment   -- > translatiors --> filters
translator（比對 tag )  
https://github.com/rime/librime/blob/0ee64d4541b66f7b9397094cdd45260bfb4ac00c/src/rime/engine.cc#L198 
     input   :  input   seg.start  seg.end   
     output : translation

filter    (比對 tags, 無 tags 表 所有 segment  )
    input:  translation
    outut:  translation     
  
https://github.com/rime/librime/blob/0ee64d4541b66f7b9397094cdd45260bfb4ac00c/src/rime/engine.cc#L189

**Comment by easyteacher** [comment]
```lua
local inputKeys = env.engine.context.input
```
