### ISSUE TITLE
可否用filter实现 笔画辅助码 筛选字词

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#121]
假设码表如下
w 我
w 瓦
w 问

那么, 键入 woi 就可以得到"问"字, 这个"oi"编码不应该写在码表里, 而是作为辅助码, 把"w"的候选进行重重筛选
如果能实现这个功能, 就再好不过了, 因为可以实现"动态码长调频"的功能
这样的话, 虽然键入的是"woi", 但是被调频的则是"w"候选中的"问"字
如果用传统的把 "woi 问"写到码表里的方式, 那么键入"woi"打出"问"字之后, "w"候选中的"问"字, 是不会被调频的

**Comment by HowcanoeWang** [comment]
写好了，请参考：[HowcanoeWang/rime-lua-aux-code: RIME输入法辅助码音形分离插件](https://github.com/HowcanoeWang/rime-lua-aux-code/tree/main)

还不稳定，请麻烦帮忙测试看看有没有其它问题~
