### ISSUE TITLE
如何用lua实现上屏

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#122]
我想把空格做成编码键, 但是又想保留上屏的功能
类似于, 编码（尾部空格）+数字1, 这样的效果
这样做是想让空格也能够调用lua脚本

**Comment by OnchiuLee** [comment]
local engine = env.engine

engine:commit_text(your_text)

**Comment by hxse** [comment]
谢谢, 试了一下, 的确发出了数字1, 可是不是选中候选, 而是直接发出去了, 有没有什么办法能够让它选中候选呢 @OnchiuLee 
![Snipaste_2021-06-05_17-29-06](https://user-images.githubusercontent.com/22582226/120887100-a471ab80-c623-11eb-8bb0-20b28875f2a1.png)
