### ISSUE TITLE
lua脚本有办法修改max_code_length的值吗

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#123]
修改 spell/max_code_length 的值, 希望修改并且能够实时生效

**Comment by OnchiuLee** [comment]
local max_code_length = env.engine.schema.config:get_int('spell/max_code_length') 获取是get_int 修改是set_int方法 目前可能做不到实时生效 自己试试

**Comment by hxse** [comment]
local max_code_length = env.engine.schema.config:get_int('spell/max_code_length')
获取到的是 nil

**Comment by OnchiuLee** [comment]
> local max_code_length = env.engine.schema.config:get_int('spell/max_code_length')
> 
> 获取到的是 nil
> 
> 
> 
> 

你没有配置肯定获取不到 在custom中配置一下就有了

**Comment by shewer** [comment]
查了librime code 只有 speller.cc 在用  
要改此參數必須在 speller 載入前修改 才能有 一次性有效

另一個方案 
在speller 前加入 lua_processor  模擬 speller  max_code_length 機制
1 將 speller/max_code_length 取出  設為 初值
2 寫回 0 
3 max_code_length: 形碼最大碼長，超過則頂字上屛〔number〕

```lua
local function init_proc(env)
     local config= env.engine.schema.config
     env.max_code_length =   config:get_int("speller/max_code_length") or 10 -- 1
     config:set_int("speller/max_code_length", 0) -- 2
end
local function func_proc(key,env)
     if  context.input > env.max_code_length then  
          --  3
    end 
    if  key:repr() ==  "hot-key"  then
                ...   env.max_code_length = new_value
    end 

end 

```

**Comment by hxse** [comment]
@shewer 请问怎样才能把lua脚本放speller 前面啊

**Comment by shewer** [comment]
把lua_processor@xxxx 放在speller 前
還是要看 engine.cc 載入程序  yaml   max_code_length 只有載入 component 前有效
yaml (利用env.engine.schema.config )的參數只會初始化時候~create component 時用一次 
  

想到一個想法

 把speller source  關於  max_code_length 程序 提到 lua_processor 中處理
利用  env 增 加 max_code_length <<----- 這樣才可以動態
speller max_code_length 設大於 lua_processor  (因爲 lua_processor 已處理 speller 不須要再做一次了)
