### ISSUE TITLE
charset_cjk_filter 放在 filters 最后的话，会导致 uniquifier 无效

### ISSUE THREAD

**Issue by funway** [hchunhui/librime-lua#128]
我一开始修改 朙月拼音 配置文件时候使用的是
```
engine/filters:
    - simplifier
    - uniquifier
    - lua_filter@charset_cjk_filter   
```
将 charset_cjk_filter 放在最后，
但是这会导致 简体朙月拼音的 uniquifier 过滤器失效。比如输入「fa」，会出现两个【发】字（一个是来自【發】，另一個來自【髮】）。

如果把 charset_cjk_filter 放在 filters 列表中的第一位，就不会出现这个问题。

**问题1:**
所以，请问这是为什么？
按照我的理解，filters 应该是按顺序来的，即使把 charset_cjk_filter 放在最后，也不应该会影响到 uniquifier 呀。

**问题2:**
另外还想请教一下，我想自己尝试写 librime-lua 脚本的话，哪里可以找到 librime 的 API 文档呀？比如我想知道 lua_filter、lua_translator 参数的定义。

**Comment by hchunhui** [comment]
问题1：这个得看 uniquifier, charset_cjk_filter 的具体逻辑。rime filter 并不都是纯函数，有些 filter 会在过滤时修改 `Candidate` 对象。所以可能会出现顺序相关的问题。

问题2：与 librime 一样没有详细的 API 文档。
基本的用法可以看 `sample` 目录下的例子。仿造这些例子应该可以解决大部分日常需求。
复杂的定制则需要您熟悉 librime。librime-lua 大部分 API 是直接封装 librime 对应的函数，它们的行为与 librime 一致。对应关系可以看 `src/types.cc`。
最后 https://github.com/TsinamLeung/librime-lua-docs 是一位开发者做的文档，可以参考。

**Comment by funway** [comment]
好的 🙏
