### ISSUE TITLE
SegmentReg   tags 設定還有較直覺的方法嗎

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#133]
lua.cc 有個 namespace SetReg 
要增刪tags 好像只能用 mt[] function call
__add  __sub __mul
```lua
local seg=env.engine.context.composition:back()
if seg then 
    print( "tags addr" , seq.tags) -- __set: xxxxxxxxx
    seg.tags= seg.tags + {ccc=true,ddd=true}  -- OK   'ccc'  ,'ddd'
    print( "new tags addr" , seq.tags) -- __set: xxxxxxxxx  tags 的addr 改變了
    
    rawset(seg.tags,"yyy",true)  -- NG  
    seg.tgs.zzz=true  -- NG
    print(seg.tags,type(seg.tags)   -- __set: xxxxxxx   \t  "table"
    for k,v in pairs(seg.tags) do print( k,v) end   --   abc   true \n ccc  true\n ddd true \n 
end
```

**Comment by hchunhui** [comment]
我的原意是希望这样用：
```lua
seg.tags = seg.tags + Set({"ccc", "ddd"})   -- union
seg.tags = seg.tags - Set({"ccc", "ddd"})   -- diff
seg.tags = seg.tags * Set({"ccc", "ddd"})   -- intersection
```

**Comment by shewer** [comment]
SetReg  __add  只檢查 table type       seg.tags + { "ccc" , "ddd"}    也有效
__add  __sub __mul    都有 for ( i=1;  i <= n ; i++)

https://github.com/hchunhui/librime-lua/blob/fff26227fc126b2e266454f932e69936ec6664d7/src/lib/lua.cc#L83-85

seg.tags +Set( {"aaa","bbb"},{"ccc","ddd"} ) + .....
seg.tags + {'aaa','bbb'} + {'ccc','ddd'}  .... -->    (seg.tags + set1) + set2    可以不用loop

**Comment by hchunhui** [comment]
虽然只检查 table type，但其实是希望都用 `Set()`，这样类型会比较清楚。
`raw_add()` 等本身应该是可以支持多个参数做并/交集，但export为运算符后只能处理两个参数了。
