### ISSUE TITLE
關於輸入數字然後自動判斷千位數增加逗號的方法？

### ISSUE THREAD

**Issue by 2ipm1nd** [hchunhui/librime-lua#14]
```lua
/*
** @maomao
** thousand add comma.
*/
function formatnumberthousands(sum)
	local function checknumber(value)
		return tonumber(value) or 0
	end
	local sum = checknumber(sum)
	local newNum = ""
	repeat
		print("value of sum:", sum)
		if sum <= 1000 then
			newNum = sum .. newNum
			return newNum
		end
		newNum = "," .. sum % 1000 ..newNum
		sum = math.floor((sum - sum % 1000)/1000) --为了得到的是整数没有.0
	until(false)
end	
```

> --------------------- 
> 版权声明：本文为CSDN博主「@maomao」的原创文章，遵循CC 4.0 by-sa版权协议，转载请附上原文出处链接及本声明。
> 原文链接：https://blog.csdn.net/m0_38138390/article/details/83834309

請問這個模組有辦法放到rime-lua，變成輸入`\\+數字`，然後自動在千位數的地方增加逗號，如輸入`\\150000`輸出變成`150,000`這樣，跪求一個**修改的方向**，不然完全不知道怎麼下手，感激不盡……

**Comment by hchunhui** [comment]
需要写一个翻译器，做三件事：
 1. 将输入串分成两部分，检查两部分是否分别是 引导符 和 数字，是则继续；
 2. 对数字部分调用转换算法（此为 `formatnumberthousands`），得到变换后的结果；
 3. `yield` 产生候选项。

具体样子参考一下样例中 `number_translator` 的实现，代码在 [sample/lua/number.lua](https://github.com/hchunhui/librime-lua/blob/master/sample/lua/number.lua) 。
这个例子将 `/数字` 转为大写，与本题结构是相似的，只是对数字具体的变换不同。
（里面 `confs`, `read_seg`, `read_number` 是转大写算法，可跳过不看。）

翻译器写完后，参考 `rime.lua` 的注释引用一下新写的模块，就可以在输入方案里面用了。

**Comment by 2ipm1nd** [comment]
> 
> 
> 需要写一个翻译器，做三件事：
> 
>     1. 将输入串分成两部分，检查两部分是否分别是 引导符 和 数字，是则继续；
> 
>     2. 对数字部分调用转换算法（此为 `formatnumberthousands`），得到变换后的结果；
> 
>     3. `yield` 产生候选项。
> 
> 
> 具体样子参考一下样例中 `number_translator` 的实现，代码在 [sample/lua/number.lua](https://github.com/hchunhui/librime-lua/blob/master/sample/lua/number.lua) 。
> 这个例子将 `/数字` 转为大写，与本题结构是相似的，只是对数字具体的变换不同。
> （里面 `confs`, `read_seg`, `read_number` 是转大写算法，可跳过不看。）
> 
> 翻译器写完后，参考 `rime.lua` 的注释引用一下新写的模块，就可以在输入方案里面用了。

感謝協助……我先以`number.lua`的檔案修改試試看能不能在rime執行，但是現在遇到一個很基本的問題無法解決，按照教學，從`number.lua`複製代碼到`rime/lua`並且將`local function translator`改名為`function number_translator`後，在bluid裡的`schema.yaml`增加`    -lua_translator@number_translator `，重新部署之後輸入`/+數字`出現這以下的畫面，但是我沒辦法輸入一個以上的數字，請問這樣是正常嗎？
![](https://i.vgy.me/gCABDA.png)

**Comment by hchunhui** [comment]
看样子 lua 函数是正确执行了，只是输入法默认不允许 `/+数字` 的输入模式。

试试加下面这个 patch
```
patch:
  'recognizer/patterns/number': '^/[0-9]+$'
```
也可以手动改 schema，在 `recognizer/patterns` 下加一行正则式：`number: ^/[0-9]+$`。

**Comment by hchunhui** [comment]
translator 套用不对，没有调用算法函数。另外摘抄的算法也有问题。

下面是我写的，供参考。

```lua
local function formatnumberthousands(n)
   local r = string.sub(n, -3, -1)  -- 从后向前取三位
   local n = string.sub(n, 1, -4)  -- 剩下的数字

   -- 每次循环从后向前取三位，拼接到结果前面
   -- 直到剩下数字为空
   while string.len(n) > 0 do
      r = string.sub(n, -3, -1) .. "," .. r
      n = string.sub(n, 1, -4)
   end

   -- 返回结果
   return r
end

function formatnumberthousands_translator(input, seg)
   if string.sub(input, 1, 1) == "/" then -- 取引导符
      local n = string.sub(input, 2, -1) -- 取参数
      if tonumber(n) ~= nil then -- 参数是数字
         local result = formatnumberthousands(n) --- 调用算法
         --[[ 用 `yield` 产生一个候选项
              候选项的构造函数是 `Candidate`，它有五个参数：
              - type: 字符串，表示候选项的类型（可随意取）
              - start: 候选项对应的输入串的起始位置
              - _end:  候选项对应的输入串的结束位置
              - text:  候选项的文本
              - comment: 候选项的注释
         --]]
         yield(Candidate("number", seg.start, seg._end, result, "千位數標示"))
      end
   end
end
```

**Comment by 2ipm1nd** [comment]
> 
> 
> translator 套用不对，没有调用算法函数。另外摘抄的算法也有问题。
> 
> 下面是我写的，供参考。
> 
> ```lua
> local function formatnumberthousands(n)
>    local r = string.sub(n, -3, -1)  -- 从后向前取三位
>    local n = string.sub(n, 1, -4)  -- 剩下的数字
> 
>    -- 每次循环从后向前取三位，拼接到结果前面
>    -- 直到剩下数字为空
>    while string.len(n) > 0 do
>       r = string.sub(n, -3, -1) .. "," .. r
>       n = string.sub(n, 1, -4)
>    end
> 
>    -- 返回结果
>    return r
> end
> 
> function formatnumberthousands_translator(input, seg)
>    if string.sub(input, 1, 1) == "/" then -- 取引导符
>       local n = string.sub(input, 2, -1) -- 取参数
>       if tonumber(n) ~= nil then -- 参数是数字
>          local result = formatnumberthousands(n) --- 调用算法
>          --[[ 用 `yield` 产生一个候选项
>               候选项的构造函数是 `Candidate`，它有五个参数：
>               - type: 字符串，表示候选项的类型（可随意取）
>               - start: 候选项对应的输入串的起始位置
>               - _end:  候选项对应的输入串的结束位置
>               - text:  候选项的文本
>               - comment: 候选项的注释
>          --]]
>          yield(Candidate("number", seg.start, seg._end, result, "千位數標示"))
>       end
>    end
> end
> ```

太感謝了！看到這樣的程式碼真的覺得貼心！弄了好幾天總算是成功了！
