### ISSUE TITLE
如何用lua进行按键拦截

### ISSUE THREAD

**Issue by hxse** [hchunhui/librime-lua#146]
比如, 打a键, 本来会作为编码键刷新候选, 但是我把它拦截住, 不让它出
以及发送按键提交候选的功能
这个功能, 可以用来做一些, 比如笔画筛选之类的辅助码功能
正常来讲, 按下编码键, 会刷新候选和编码, 同时进入lua脚本, 但是希望能把该按键拦截, 不刷新候选和编码, 但是lua脚本可以捕捉到这个按键键值, 做一些处理

**Comment by shewer** [comment]
https://github.com/rime/librime/blob/62a97cf64a75fe86140dfb3f4be5f5c1adfe0e07/src/rime/engine.cc#L98
攔截~~keyevent 是 engine - >processors 工作
engine 會一個一個 processor 循問 


```lua
function processor_func(key,env) -- lua_processor@xxx 
  local kRejected, kAccepted, kNoop = 0,1,2
  local context= env.engine.context
  if key:repr() == "a" then 
      context:push("a")  -- 將~~ a 加入 context.input
      return kAccepted  -- 收下此~~key  
  elseif key:repr() == "b" then 
      return kRejected   --  librime 不處理
 elseif key:repr() == "c" then 
       return kNoop   -- 此~~processor 不處理
 elseif key:repr() == "d" then 
      
 end
  return kNoop  
end 
```

**Comment by hxse** [comment]
我把这个脚本写进 xxx.schema.yaml 文件的 engine/processors/lua_processor@xxx 但是没有效果, 不知道怎么用

**Comment by hxse** [comment]
@shewer 像这种lua_processor我从来没弄成功过, 普通的lua脚本都是可以的啊
