### ISSUE TITLE
【求助】是否可以用lua实现循环选重

### ISSUE THREAD

**Issue by mokapsing** [hchunhui/librime-lua#148]
如题, LUA可以拦截并动态替换key吗，并非是key_binder中固定替换

举个例子：（因为我使用的是script_translator+仓颉）当我输入编码`yk`时候选栏有完全匹配编码的重码候选【文】【头】【达】，和不完全匹配的候选【卜】
![image](https://user-images.githubusercontent.com/39441028/141480258-dc3175ca-e86a-456a-9cfa-2ff42da58a2a.png)

大概的意思是想做一个键，可以在完全匹配的重码候选中进行一个循环Up↑/Down↓，当第1个选中，按下该键，则第2个选中，再按下该键，则第3个选中，再按下又回到第一个，如此反复。

希望有大佬指点迷津

**Comment by shewer** [comment]
增加 lua_filter   重排candidate  , candidate.type 可以判斷  not  "completion" 重排 candidate 數量
增加 keybind 觸發 option 
option_update_notifier() 調整 candidate 循環順序 index
context.input有變動時  index 清0
以下範例 不一定是正確的，沒有測試過

```lua
 --- add keybind {when: has_menu , accept: "0" , set_option: "reorder_cand" }

 local function init(env)
    local context= env.engine.context
    env.index = 0
    env.input=""  --
    env.option_update= context.option_update_notifier:connect( function(ctx,name)
      if name == "reorder_cand" then
        env.index += 1
      end
    end )

 end

 local function fini(env)
    env.option_update:disconnect()
 end

 local reorder_cands(cands,index)
   for i=1,index do  -- index 0
     local cand=table.remove(cands,1)
     table.insert(cands,cand)
   end
   return cands
 end

 local function func(inp,seg,env)
   local  context= env.engine.context
   -- reset env.input and clear env.index
   if env.input ~= context.input then
     env.index= 0
     env.input=context.input
   end

   local is_completion= false
   local cands={}
   for cand in inp:iter() do
     is_completion = is_completion and cand.type == "completion"
     if not is_completion then
       table.insert(cands,cand)
     else
       if #cands >0 then
         reorder_cands(cands,index)
         repeat
           yield ( table.remove(cands,1) )
         until #cands <= 0
       end
       yield(cand)
     end
   end
 end

return {init=init, fini=fini , func=func}
```

**Comment by mokapsing** [comment]
首先非常感谢，这么快就有回复，幸苦大佬了

说回脚本，目前这个脚本应该是有些问题的，我把它作为最后一个filter，现在我只能看到我输入的原始英文编码，没有一个候选字

**Comment by shewer** [comment]
你可以試試檢查 ，會不會是 cand.type 對不上
```lua
function func(inp,env)
    for cand in inp:iter() do 
         cand.comment= cand.type
          yield(cand)
    end
end 
```
另外還可以查 log file

**Comment by mokapsing** [comment]
> 你可以試試檢查 ，會不會是 cand.type 對不上
> 
> ```lua
> function func(inp,env)
>     for cand in inp:iter() do 
>          cand.comment= cand.type
>           yield(cand)
>     end
> end 
> ```
> 
> 另外還可以查 log file

原来它们所是 phrase

**Comment by shewer** [comment]
编码yk时候选栏有完全匹配编码的重码候选【文】【头】【达】，**和不完全匹配的候选**【卜】

不完全匹配爲何會上屏候選呢？
爲何 candidate 都是 phrase(拼音:script_translator) 
 爲何 candidate.type =="phrase" 會沒有候選字呢

**Comment by mokapsing** [comment]
```lua
function func(inp,env)
    local  context= env.engine.context
    
    for cand in inp:iter() do 
         if string.len(context.input) == cand._end then
             cand.comment= "full-matched"
             
		 else
		     cand.comment= "partly-matched"
		 end
		 yield(cand)
    end
end
```

这样好像可以区分完全和不完全

**Comment by mokapsing** [comment]
> 编码yk时候选栏有完全匹配编码的重码候选【文】【头】【达】，**和不完全匹配的候选**【卜】
> 
> 不完全匹配爲何會上屏候選呢？ 爲何 candidate 都是 phrase(拼音:script_translator) 爲何 candidate.type =="phrase" 會沒有候選字呢

```log
Log file created at: 2021/11/13 12:53:14
Running on machine: 上网桌面0002
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1113 12:53:14.418233  1096 lua_gears.cc:44] Lua error:(2): C:\Program Files (x86)\Rime\usr\lua\loop_completion.lua:7: attempt to index a nil value (field 'option_update_notifier')
E1113 12:53:14.423116  1096 lua_gears.cc:15] LuaTranslation::Next error(2): C:\Program Files (x86)\Rime\usr\lua\loop_completion.lua:29: attempt to index a nil value (local 'env')
E1113 12:53:14.423116  1096 lua_gears.cc:15] LuaTranslation::Next error(2): C:\Program Files (x86)\Rime\usr\lua\loop_completion.lua:29: attempt to index a nil value (local 'env')

```

**Comment by mokapsing** [comment]
> 编码yk时候选栏有完全匹配编码的重码候选【文】【头】【达】，**和不完全匹配的候选**【卜】
> 
> 不完全匹配爲何會上屏候選呢？ 爲何 candidate 都是 phrase(拼音:script_translator) 爲何 candidate.type =="phrase" 會沒有候選字呢

有候选，是输入第一个编码时，不会有候选，输入第二个编码时出现正确的候选

**Comment by mokapsing** [comment]
> 编码yk时候选栏有完全匹配编码的重码候选【文】【头】【达】，**和不完全匹配的候选**【卜】
> 
> 不完全匹配爲何會上屏候選呢？ 爲何 candidate 都是 phrase(拼音:script_translator) 爲何 candidate.type =="phrase" 會沒有候選字呢

没有候选输出是因为func多了一个参数，去掉了就可以了，且只会出一个候选，现在是init那有问题

**Comment by shewer** [comment]
https://github.com/rime/librime/releases/tag/1.7.2    rime-with-plugins
librime 版本??

**Comment by mokapsing** [comment]
> https://github.com/rime/librime/releases/tag/1.7.2 rime-with-plugins
> librime 版本??

确实是版本的问题，现在可以循环候选了，但是是全部循环，没有去掉部分匹配项

**Comment by shewer** [comment]
> > https://github.com/rime/librime/releases/tag/1.7.2 rime-with-plugins
> > librime 版本??
> 
> 确实是版本的问题，现在可以循环候选了，但是是全部循环，没有去掉部分**匹配项**

怎麼定義  匹配項  如何排列 怎麼檢查

**Comment by mokapsing** [comment]
> > > https://github.com/rime/librime/releases/tag/1.7.2 rime-with-plugins
> > > librime 版本??
> > 
> > 
> > 确实是版本的问题，现在可以循环候选了，但是是全部循环，没有去掉部分**匹配项**
> 
> 怎麼定義 匹配項 如何排列 怎麼檢查

```lua
string.len(context.input) == cand._end
``` 可以判断是不是完全匹配，顺序最好是按照原来的顺序

**Comment by shewer** [comment]
不知遒 
怎麼定義 匹配項 未處理前排列如何 怎麼檢查
cand.comment =   cand.type  ..  "---" .. cand.start .. ":" .. cand._end 
yield(cand)

**Comment by mokapsing** [comment]
> 不知遒 怎麼定義 匹配項 未處理前排列如何 怎麼檢查 cand.comment = cand.type .. "---" .. cand.start .. ":" .. cand._end yield(cand)

![image](https://user-images.githubusercontent.com/39441028/141640726-ec824091-a283-44e1-a10e-ef257513066e.png)

**Comment by mokapsing** [comment]
@hchunhui 这种日志是什么意思呢 

```log
Log file created at: 2021/11/13 20:17:48
Running on machine: DESKTOP-7DUJJ49
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1113 20:17:48.567121  4372 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter
E1113 20:17:48.568118  4372 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter
```

**Comment by mokapsing** [comment]
@shewer 目前可以循环候选项，我发现只要在遍历时跳过不完全匹配的cand就可以达到我的目的了

**Comment by shewer** [comment]
恭喜完成

**Comment by mokapsing** [comment]
> 恭喜完成

感谢指点
