### ISSUE TITLE
lua产生的候选词位置

### ISSUE THREAD

**Issue by Konfido** [hchunhui/librime-lua#15]
如题，请问怎么修改，可以手动修改lua脚本产生的候选词位置

**Comment by hchunhui** [comment]
可以详细一些吗？

这个回答有没有帮助？
https://github.com/hchunhui/librime-lua/issues/12#issuecomment-504852490

**Comment by Konfido** [comment]
十分感谢，已参照 [#12 (comment)](https://github.com/hchunhui/librime-lua/issues/12#issuecomment-504852490) 完成权重修改。

建议：在Candidate中添加quality参数，或设置较高默认值。（直觉上，如果用到了lua脚本，大概率希望其产生的候选词位置靠前。）
