### ISSUE TITLE
Add a license and tag commits.

### ISSUE THREAD

**Issue by Vonfry** [hchunhui/librime-lua#153]
I want to pack this package on a distribution. Would you like to add a license and tags?

**Comment by hchunhui** [comment]
Sure. I should have done it earlier. It was intended to be merged into librime, but now it's an external project. I will commit the same license as librime.

For tags, what should I do (follow some naming conventions, etc) ? Can you just use the commit id?

**Comment by Vonfry** [comment]
> For tags, what should I do (follow some naming conventions, etc) ? Can you just use the commit id?

Commit id can be used. A tag can help bots to check and update
automatically. Tags means stable and commits means unstable. Now I use
commits directly which is not a big issue.

**Comment by hchunhui** [comment]
OK. I have commit the license. I will add tags in the future if the project is stable enough.
