### ISSUE TITLE
如何实现首词首字功能

### ISSUE THREAD

**Issue by Cirn09** [hchunhui/librime-lua#155]
比如我现在候选第一位是“毕设”，那我按下<kbd>[</kbd>就能打出“毕”，按下<kbd>]</kbd>就能打出“设”

以及这项目能写份文档吗，sample里展示了一些简单的应用场景和API，issue里又能搜到其他API的使用简单范例

**Comment by shewer** [comment]
以詞定字  https://github.com/shewer/librime-lua-script/blob/main/README.md#%E4%BB%A5%E8%AF%8D%E5%AE%9A%E5%AD%97

**Comment by Cirn09** [comment]
https://github.com/BlindingDark/rime-lua-select-character
