### ISSUE TITLE
如何修改 simplifier 返回的 comment？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#16]
已通过修改 `cand:get_genuine().comment` 实现修改候选注释，但是对 simplifier 返回的候选无效，对其余候选有效。

**Comment by Ace-Who** [comment]
lua_filter 是排在后面的：

```yaml
engine/filters:
    - charset_filter@gb2312
    - charset_filter@gbk
    - charset_filter@big5
    - charset_filter@utf8
    - simplifier@simplify
    - lua_filter@post_processor
```

**Comment by hchunhui** [comment]
要设一下 `simplifier` 的 `comment_format`，将注释置为空，`cand:get_genuine().comment` 的修改才有效。

否则好像办不到，原因如下：

首先， `simplifier` 返回的类型是 `ShadowCandidate`， librime 没有提供修改这种类型注释的接口。

用 `cand:get_genuine().comment` 也不行。这是因为当 `ShadowCandidate` 自己的注释不为空时，它总是会显示自己的注释，而忽略底层候选的注释。

**Comment by Ace-Who** [comment]
谢谢。结合我的测试，总结一下，读取 simplifier 返回的非空注释是可以的，修改它也是可以的，但是要显示为同一个候选的注释，是办不到的。
