### ISSUE TITLE
在lua_filter中調用lua_translator的方法

### ISSUE THREAD

**Issue by ianzhuo** [hchunhui/librime-lua#165]
在`reverse.lua`範例中，可以透過`lua_filter`查詢`*.reverse.bin`的內容
```
local function reverse_lookup_filter(input, pydb)
   for cand in input:iter() do
      cand:get_genuine().comment = cand.comment .. " " .. xform_py(pydb:lookup(cand.text))
      yield(cand)
   end
end
```

在`expand_translator.lua`範例中，可以透過`lua_translator`查詢`*.table.bin`的內容
```
local function translate(inp,seg,env)
```
想請教的是，該如何將lua_filter的反查結果(cand.text)，作為translate的參數(inp)送入lua_tranlator進行查詢呢？

**Comment by shewer** [comment]
反查 會得到 字根碼   0組或多組 以空格間隔
```lua
  str= lookup(cand.text)  or ""
  tab = {}
  for code in string:gmatch("[^%s]+") do 
      table.insert(tab,code)
  end
  print(#tab) 
  
```
用 MemoryReg api  打開字典 並用  code 查詢 
參考 example code


lua_translator
func(input,seg,env) -- input: context.input(string)  , seg: segment , env: table
lua_filter(inp,env) -- inp: translation , env :table

TranslationReg   api   iter()
for cand in  inp:iter() do 
     ....
end

**Comment by ianzhuo** [comment]
感謝@shewer ，因為查不太的到TranslationReg 的呼叫範例，
下列是依據您提供的線索建立的一組lua_filter，在`init(env)`初始化`env.t1 = Translator(engine,"translatior" , "lua_translator@date")`，目標是把反查得出的地球拼音多組字根碼以「的」為例共有「de5、 di2、 di4」 三組字根碼，在`reverse_lookup_filter(input, pydb)`函數中送入lua_translator@date 進行查詢。
 
但實在不太知道TranslationReg 具體建立方式，能請您幫忙看一下嗎？

```lua
local function reverse_lookup_filter(input, pydb)
	for cand in input:iter() do
		str = pydb:lookup(cand.text)  or ""
		tab = {}
		for match in (str.." "):gmatch("(.-)".." ") do
			table.insert(tab, match)
		end
		
		for k,v in pairs(tab) do
			yield(Candidate("w2c", cand.start, cand._end, cand.text .. " " .. v ,  '地球拼音'))
			
--			以lua_translator@date 進行查詢???
			local t=env.t1:query(input,seg)
			:pipe( function(tran) for cand in tran:iter() do 
				 .... yield(cand)  
				  end 
			end)
		end
	end
end

local function filter(input, env)
	b = env.engine.context:get_option("liu_w2c")

	if(b) then
		reverse_lookup_filter(input, env.pydb)
	else
		for cand in input:iter() do
		  yield(cand)
		end
	end
end

local function init(env)
--   建立地球拼音反查
   env.pydb = ReverseDb("build/terra_pinyin.reverse.bin")
   
--   建立 TranslationReg lua_translator@date 
   env.t1 = Translator(engine,"translatior" , "lua_translator@date")
end

return { init = init, func = filter }
```

**Comment by shewer** [comment]
有 Translator() 這個Api嗎? 沒有印象
你可以在 ISSUE 搜 translation 看看

librime-lua 目前無法create component ( processor segmentor translator filters
用lua_trasnlator@date 調反查??, 建議另外做一個module 

不大懂你是要 注音輸入 反查形碼字根  所有cand.text反查注音字根

**Comment by ianzhuo** [comment]
Hi,
我是想透過lua_filter作同音字查詢，
1.lua_filter可以達成 形碼->反查地球拼音
2.expand_translator 可以用lua以地球拼音方案查單字

我想達成的是把上面兩步結合起來，直接形碼->反查拼音->查同音字

> 有 Translator() 這個Api嗎? 沒有印象 你可以在 ISSUE 搜 translation 看看
> 
> librime-lua 目前無法create component ( processor segmentor translator filters 用lua_trasnlator@date 調反查??, 建議另外做一個module
> 
> 不大懂你是要 注音輸入 反查形碼字根 所有cand.text反查注音字根

**Comment by DreamAfar** [comment]
> @shewer谢怜，原来原来在init(env)里面的memoryreg就可以查出搜索结果了，现在已经只需要直接完成点解相关功能了。

你好，请问你后面是怎么将lua_filter的反查结果（cand.text），作为翻译的参数（input）送入lua_tranlator进行查询
或在init(env)里面的memoryreg就可以查出搜索结果的呢？
能否提供下lua参考下
我是想直接根据输入的中英文编码->截取出一段编码来查英文->拼接生成中英文整句混合输入候选词

**Comment by shewer** [comment]
我目前沒有用 MemoryReg 你可以參照memoryReg範例產生 candidate
processors --> segmentors --> translator --> filters 無法回到上面

用修改 context.input  太複雜  要注意的事項反而難搞. 

lua_filter 內反查的字根 當作 input   在memory api 送 可以 用  
for pharse in  memory:iter(...) do 
   local cand=pharse.to_candidate ( 查一 下 PhraseReg) 
    ......
    yield(cand)
end

如果有英文字典就會有英文的candidate  只是排在下面
