### ISSUE TITLE
如何读取配置中 menu/page_size 的值？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#17]
尝试阅读源代码，但不懂，想结合一个例子来理解。
尝试了 `env.schema.config:get_int('menu/page_size')`，没成功。

**Comment by hchunhui** [comment]
`schema` 在 `env.engine` 里面：
`env.engine.schema.config:get_int('menu/page_size')`，这样可以。

**Comment by Ace-Who** [comment]
成功了，谢谢。

**Comment by Ace-Who** [comment]
看了源代码，专门定义了 `env.engine.schema.page_size`，也可以。
