### ISSUE TITLE
Phrase  無法調用 Candidate member function 

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#174]
真被搞懞了
Phrase : public Candidate
type start end quality  好像不能 直接 WRAPMEM(T:type) ..... 註冊
調用不到
local ph = Phrase( mem, type, start, _end , entry) 
只要用 ph.type   , ph.quality ....    
E20220704 21:45:53.898211 3490189 lua_gears.cc:15] LuaTranslation::Next error(2): bad argument #2 to '?' (7LuaTypeIRKN4rime9CandidateEE expected)

難道 真得用 WRAP()

**Comment by hchunhui** [comment]
`lua_templates.h` 现在还不支持类继承，对类型检查过于严格。临时只能用 `WRAP()` 中转一下。先合并你的 pull request 了，以后找时间再系统地解决这个问题。

**Comment by hchunhui** [comment]
`WRAPMEM` 改进了。写法有一些区别，原来是 `WRAPMEM(T::member)`，现在增加了 `WRAPMEM(T, member)` 的两参数写法。新写法下可以避免报错。

**Comment by shewer** [comment]
太棒了，  
同名異式 應仍要用 WARP吧

**Comment by hchunhui** [comment]
对，同名的情况还是无解。
