### ISSUE TITLE
config:is_list 返回值异常

### ISSUE THREAD

**Issue by LawssssCat** [hchunhui/librime-lua#193]
测试发现当配置不存在时候 is_list 返回 true

![image](https://user-images.githubusercontent.com/18041500/190287058-f2205900-0a7b-4d7c-b76b-b6f9ec67da00.png)

不知道哪里的问题

librime-lua:

https://github.com/hchunhui/librime-lua/blob/b695487fa947b14d59ff6d6f2e5f3eae15f6fecc/src/types.cc#L1020

librime:

https://github.com/rime/librime/blob/8888b6da90be329efde2a584389617cbc82be352/src/rime/config/config_types.cc#L225-L228

**Comment by shewer** [comment]
librime 空值的path  表 true
因爲 list map value 都可以設
看到你語法
可以做成 
```lua
--assert_error( config:get_list('engine/filters'),true,"test")
function assert_error(obj, res ,msg)
   msg = msg or ""
   if obj ~= res then
        log.error( ("assert error: %s : %s ~= %s"):format(msg,obj,res))
   end
end
```
https://github.com/rime/librime/blob/87e4c73f50e59472817facab3b4fb67e37e81cde/src/rime/config/config_component.cc#L52

**Comment by LawssssCat** [comment]
>https://github.com/rime/librime/blob/87e4c73f50e59472817facab3b4fb67e37e81cde/src/rime/config/config_component.cc#L52

我 librime 看这段代码

```c
bool Config::IsList(const string& path) {
  auto p = data_->Traverse(path);
  return !p || p->type() == ConfigItem::kList;
}
```

意思是这样吗？
1. 空 时 true （疑问）
2. 非空且为list 时 true
3. 非空且非list 时 false

为啥怎么设计？历史原因？

@shewer  @lotem

**Comment by shewer** [comment]
config data 是依循 yaml
我認爲是爲了依循yaml吧
空的path你想加 map list value 都可以
如果是有值 就得 確認
