### ISSUE TITLE
请问调用memory前，编码如何按韵母（元音/圓音）分开？

### ISSUE THREAD

**Issue by LawssssCat** [hchunhui/librime-lua#202]
测试发现，使用 memory:user_lookup 查询的字符串（如果有多个元音）需要按韵母（元音/圓音）分开，否则无法查询到结果

请问调用 memory:user_lookup 前，可以调用哪个方法把编码按韵母（元音/圓音）分开？

```lua
function translator.func(input, seg, env) ---------------------- input 没有分割 “nihao”
  local context = env.engine.context
  env.mem = Memory(env.engine,env.engine.schema) 
  mem:user_lookup("ni hao", true) -- -------------------------- 中间需要空格分割 “ni hao”
  -- 遍历用户字典
  for entry in mem:iter_user() do
    logger.error(entry.text)
  end
end

-- 查询结果
你好
李豪
你好
...

-- 用户字典
ni hao	你好	c=45 d=42.7988 t=3067
ni hao	李豪	c=20 d=19.9501 t=3069
ni hao 	你好	c=53 d=12.9956 t=3192
ni hao a 	你好啊	c=0 d=0.107187 t=3192
ni hao a a a a a a a bi sha	你好啊啊啊啊啊啊啊必杀	c=1 d=1 t=2849
ni hao a a a a a a a bi sha 	你好啊啊啊啊啊啊啊必杀	c=1 d=0.97531 t=3192
```

**Comment by shewer** [comment]
https://github.com/rime/librime/blob/87e4c73f50e59472817facab3b4fb67e37e81cde/src/rime/gear/script_translator.cc#L104
應該是要自己切吧  script_translator 太複雜

**Comment by shewer** [comment]
很是好奇你爲何要看 2015 的版本 ，建議看librime 1.5.3 2019 ([小狼毫 0.14.3](https://github.com/rime/weasel/releases/latest) 以後版本，這應該是較好的選擇，且版本差異很大
2015 -
https://github.com/rime/librime/blob/1246d21cb188e850c88d50c6e6d61e0763efd30e/include/rime/gear/script_translator.h
2019-
https://github.com/rime/librime/blob/719542c9bc9fd941cd6fb977b2998557b0be5122/src/rime/gear/script_translator.h

代碼接口沒有在 head file 宣告不好調用，
有沒有考慮先用   Component.Translator 調出 script_translator 的translation後再整理
從 candidate 中 preedit  commit( enable_hist) 中取出 'ni hao'

( lua 比 c++ 慢20倍(如果要全運算) , 在ui中可能沒有感覺)

mem:user_dict("ni" , true, 1000) -- true 未全碼也可調出 'ni hao' **如果 user_dict 有data**
可以 用gsub 移去 space 再比對，因為我測試 nihao  產出的candidate 是Phrase 而不是 UserPhrase,表示並非調用 user_data

```lua
--init 
env.tran=Component.Translator(env.engine,'','script_translator@luna_pinyin')


-- func 
   for cand in env.tran:query(inp,seg):iter() do
       if  utf8:len(cand.text) > 1 then
           active_inp = cand.preedit
            ....
       end 
   end
```

**Comment by LawssssCat** [comment]
> 很是好奇你爲何要看 2015 的版本 ，建議看librime 1.5.3 2019 ([小狼毫 0.14.3](https://github.com/rime/weasel/releases/latest) 以後版本，這應該是較好的選擇，且版本差異很大 2015 - https://github.com/rime/librime/blob/1246d21cb188e850c88d50c6e6d61e0763efd30e/include/rime/gear/script_translator.h 2019- https://github.com/rime/librime/blob/719542c9bc9fd941cd6fb977b2998557b0be5122/src/rime/gear/script_translator.h
> 

2015 应该那段代码是最后一次修改的版本， vscode gitlens 帮忙找的

**Comment by LawssssCat** [comment]
> 有沒有考慮先用 Component.Translator 調出 script_translator 的translation後再整理 從 candidate 中 preedit commit( enable_hist) 中取出 'ni hao'
> 
> ```lua
> --init 
> env.tran=Component.Translator(env.engine,'','script_translator@luna_pinyin')
> 
> 
> -- func 
> 
> local function split_words(cand)
>    local tab ={} 
>    for word in cand.preedit:gmatch("[^%s]+") do
>        table.insert(tab,word)
>    end
>    for i,v in ipairs(tab) do 
>      tab[i] = {v,utf8.sub(cand.text,i,i}
>    end
>    return tab
> end
>    for cand in env.tran:query(inp,seg):iter() do
>        if  utf8:len(cand.text) > 1 then
>            active_inp = cand.preedit
>                 local words = split_words(cand)
>                -- ...
>             end
>             ....
>        end 
>    end
> ```

通过 Component.Translator 調出 script_translator 的效果是不是和 filter 得到的 cand 一样？

*.schema.yaml
```yaml
engine:
  filters:
    - "lua_filter@my_user_dict_filter"
  translators:
    - script_translator
```

my_user_dict_filter
```lua
local filter = {}
function filter.func(input, env)
    for cand in input:iter() do

       local ps = cand.preedit
       -- ..

   end
end

return filter
```

可我觉得 filter 中得到的候选词挺奇怪的：

一些用户词典的词，像 `ni hao a 	你好啊	c=0 d=0.107187 t=3192` 可以得到候选词
一些用户词典的词，像 `chun ying wen 	純英文	c=1 d=0.29671 t=3192` 又得不到候选词

中间找不到什么规律

所以才想用  memory:user_lookup  直接查用户字典

**Comment by shewer** [comment]
不是被 Shadow 了嗎 
    { "ShadowCandidate", WRAP(shadow_candidate) },
    { "UniquifiedCandidate", WRAP(uniquified_candidate) },
你搜尋一下 code  有那些 component 會用 應該不多  記得 uniquilfier   simplifier

**Comment by LawssssCat** [comment]
大概是 simplifier 的这一段
https://github.com/rime/librime/blob/fa93161528293abf799991e95d1d4e37d0c84a83/src/gear/simplifier.cc#L189-L194
```c
```

**Comment by LawssssCat** [comment]
大概是 simplifier 的这一段，opencc 匹配成功编成 shadow candidate
（但是搞不清楚什么时候 opencc 匹配成功）
https://github.com/rime/librime/blob/fa93161528293abf799991e95d1d4e37d0c84a83/src/gear/simplifier.cc#L189-L194
```c
class Opencc {
 public:
  bool ConvertWord(const string& text, vector<string>* forms) {
    if (dict_ == nullptr) return false;
    opencc::Optional<const opencc::DictEntry*> item = dict_->Match(text);
    if (item.IsNull()) {
      // Match not found
      return false;
    } else {
      const opencc::DictEntry* entry = item.Get();
      for (auto&& value : entry->Values()) {
        forms->push_back(std::move(value));
      }
      return forms->size() > 0;
    }
  }
};

bool Simplifier::Convert(const an<Candidate>& original,
                         CandidateQueue* result) {
  if (excluded_types_.find(original->type()) != excluded_types_.end()) {
    return false;
  }
  bool success = false;  ------------------------------------------------- success 成功则变成 shadow candidate
  if (random_) {
    string simplified;
    success = opencc_->RandomConvertText(original->text(), &simplified);
    if (success) {
      PushBack(original, result, simplified);
    }
  } else { //!random_
    vector<string> forms;
    success = opencc_->ConvertWord(original->text(), &forms);
    if (success) {
      for (size_t i = 0; i < forms.size(); ++i) {
        if (forms[i] == original->text()) {
          result->push_back(original);
        } else {
          PushBack(original, result, forms[i]);
        }
      }
    } else {
      string simplified;
      success = opencc_->ConvertText(original->text(), &simplified);
      if (success) {
        PushBack(original, result, simplified);
      }
    }
  }
  return success;
}
void Simplifier::PushBack(const an<Candidate>& original,
                         CandidateQueue* result, const string& simplified) {
...
  result->push_back(
      New<ShadowCandidate>(
          original,
          "simplified",
          text,
          tips,
          inherit_comment_));
}
```

我尝试把 simplifier 注释了，确实全部 shadow 变回了 phrase

**Comment by shewer** [comment]
在simplifier 中 的 translation  調用 opencc:Convert  三個其中一個 
cand:get_genuine() 就可以轉出 parse candidate 
rime 的  translator( translation) - filter(translation) -->filter(translation) -.....-> menu
類似拖拉的方式 一頁一頁拉出 final candidate

**Comment by LawssssCat** [comment]
是不是 Phrase 被选中会记录到用户字典，但是 ShadowCandidate 包裹的 Phrase 被选中不会记录到用户字典？

**Comment by LawssssCat** [comment]
librime-lua 的 phrase 也没有 set text 方法，

是不是因为 phrase 的 text 是没法改的，所以才用 Shadow Candidate 在外面包一层？ 😂

https://github.com/hchunhui/librime-lua/blob/15bd231e46fb5c0c7dd8a81d2d30fee9a838f0fa/src/types.cc#L1420
https://github.com/hchunhui/librime-lua/blob/15bd231e46fb5c0c7dd8a81d2d30fee9a838f0fa/src/types.cc#L1463-L1472

**Comment by shewer** [comment]
只有 SimpleCandidate 可以改text
另外 librime-lua 2021 還沒有可以用 WRAPMEM( T, methods) 部份 WRAPMEM() 無法註冊到
parants method return  空值 或 error
這段是有點問題  type start _end  是 Candidate的method 在此會有問題的
可能是沒有人遇到或忽略吧


https://github.com/rime/librime/blob/87e4c73f50e59472817facab3b4fb67e37e81cde/src/rime/candidate.cc#L11-L35
有點繞     L20  有 UnpackShadowCandidate

**Comment by LawssssCat** [comment]
用 lua 实现了个简单的 分词：

https://github.com/LawssssCat/rime-aurora/blob/bb6842b12d6a29e4d0e6f40ebb42cb98548ab28b/lua/tools/string_syllabify.lua

单元测试：

https://github.com/LawssssCat/rime-aurora/blob/a2004f10e072f1a0c8f86dff674b09322cd5261d/lua/test/test_string_syllabify.lua
