### ISSUE TITLE
疑问：在 filter 的 input:iter() 中不调用 yield 方法，是否会进入死循环？

### ISSUE THREAD

**Issue by LawssssCat** [hchunhui/librime-lua#203]
filter 中我想把 cand 先遍历一遍，遍历途中不 yield cand，而是做些处理存进 arr 中，然后再遍历 arr 进行 `yield(cand)`。

```lua
function filter.func(input, env)
  local arr = {}
  for cand in input:iter() do
    table.insert(arr, cand)
    -- yield(cand) ---------------------- iter 中不 yield
  end
  for i, cand in pairs(arr) do
    -- 处理
  end
end
```

**然后就进入莫名其妙进入死循环** ❓

（简化成只有一个 iter 循环，依然死循环）

```lua
function filter.func(input, env)
  for cand in input:iter() do
    -- yield(cand) ---------------------- iter 中不 yield
  end
end
```

当我把 iter 中的注释 yield 放开，就没有死循环了

```lua
function filter.func(input, env)
  local arr = {}
  for cand in input:iter() do
    table.insert(arr, cand)
    yield(cand) ----------------------- 注释放开，iter 中 yield
  end
  for i, cand in pairs(arr) do
    -- 处理
  end
end
```

请问是否是设计成这样的？（还是我个人代码上下文导致的情况？）

**Comment by LawssssCat** [comment]
看 Translation 的 iter 方法，没看出和 yield 的关系 

https://github.com/hchunhui/librime-lua/blob/2655a3081cc1bdfe1257c9c0145e4576d2d221e6/src/types.cc#L238-L251

**Comment by shewer** [comment]
translation -> filter (translation) --> filter( translation) --> ...... ---> 
記得我說過  拖拉 嗎   
最好不要存一堆arr 再 yield  ，如果運算太多 拉慢上屏 會有出字慢的感覺

lua_filter func    就是產生 translation 交給下一個filter  ,如果不 yield(cand) 不就阻斷了


function filter.func(inp,env)  end  -- 全過瀘
function filter.func(inp,env)   -- bypass 
   for cand in inp:iter() do yield(cand) end 
end

**Comment by LawssssCat** [comment]
也没有存一堆 arr，后面试了一种情况

跟全过滤差不多
```lua
function filter.func(inp,env) end -- 全過瀘
```

就是多了  iter ，然后就死循环了

```lua
function filter.func(input, env)
    for cand in input:iter() do
    end
end
```

**Comment by shewer** [comment]
> 也没有存一堆 arr，后面试了一种情况
> 
> 跟全过滤差不多
> 
> ```lua
> function filter.func(inp,env) end -- 全過瀘
> ```
> 
> 就是多了 iter ，然后就死循环了
> 
> ```lua
> function filter.func(input, env)
>     for cand in input:iter() do
>     end
> end
> ```
井沒有進入死循環 ( 可能 translation candidate 太多，要等一下) 
上式和 空func 差別在多一個空循環
```lua
 function filter.func(input, env)
     for cand in input:iter() do
     end
     yield(
          Candidate('---',1,3,'------------','-----------')
      ) 
end
```

**Comment by LawssssCat** [comment]
> 
> 井沒有進入死循環 ( 可能 translation candidate 太多，要等一下) 上式和 空func 差別在多一個空循環
> 

我的理解是 `input:iter()` 会根据现有的候选词数量（`yield`次数） 来决定是否返回空（以结束循环）吗？

也就是一直不 yield ，就会一直遍历，直到遍历完整个码表，从而出现一种死循环的假象？

**Comment by shewer** [comment]
> > 井沒有進入死循環 ( 可能 translation candidate 太多，要等一下) 上式和 空func 差別在多一個空循環
> 
> 我的理解是 `input:iter()` 会根据现有的候选词数量（`yield`次数） 来决定是否返回空（以结束循环）吗？
> 
> 也就是一直不 yield ，就会一直遍历，直到遍历完整个码表，从而出现一种死循环的假象？

沒人知道 filter  接收上一個 translation 會有多少 candidates 
可能上千 可能 只有幾個 (table_tran )

以篩選 單字 filter 舉例:     只yield   單個字 的 其他不yield  
```lua
   for cand in inp:iter() do 
        if utf8:len(cand.text) == 1 then 
              yield(cand)
        end
    end
```

**Comment by LawssssCat** [comment]
> 沒人知道 filter 接收上一個 translation 會有多少 candidates 可能上千 可能 只有幾個 (table_tran )

谢谢， 大概知道假死的原因了。

本来觉得 filter uniquifier 去重不彻底，想用 lua 实现的。

但如果没法遍历完再 yield 的话，应该是没戏了

**Comment by shewer** [comment]
我也曾想 做 uniquifier   但是 牽涉到 UniquiCandidate  和 commit 詞頻
為了不 影響 user_db 而作罷
uniquifier 去重不會不徹底 反而是太徹底 (  tags 沒有作用 )

目前還沒有要用  lua_filter + UniquiCandidate  作 lua_fillter 的 uniquifier  的時機

**Comment by LawssssCat** [comment]
功能需要（设定去重优先级），还是实现了一个 filter 去重。不过效果确实不好 😂。去重范围设定成1000个候选词就开始会卡了。（0.3s左右延迟）

https://github.com/LawssssCat/rime-aurora/blob/b61f6693f997d97a46385bb678f248718d6bf760/lua/my_uniquifier.lua

我感觉卡顿的原因是 lua 的 table 无法（或者我不知道如何）预先分配空间，要经常 rehash 导致的。不是很熟悉 lua 语言，不知道怎么解决 ಥ_ಥ

**Comment by shewer** [comment]
新版 增加 ShadowCandidate  UniquifiedCandidate
沒有 這兩個 candidate class 操作是麻煩的
還有不要用 輪循完 iter() ， 再上候選 

```lua
function filter.func(inp,env)
    local keep_first_cand={}  -- key: cand.text  value: candidate
    for cand in inp:iter() do 
        if not keep_first_cand[ cand.text ] then
            local u_cand = UniquifiedCandidate(cand)
            keep_first_cand[ cand.text] = u_cand
            yield(u_cand)
        else 
            keep_first_cand[cand.text]:append(cand)
        end
    end
end
```

**Comment by LawssssCat** [comment]
原来 UniquifiedCandidate 是这么用的，谢谢，我大概知道怎么改了

**Comment by LawssssCat** [comment]
抱歉，还是有问题，

请问这个 append 方法给 uniquified Candidate 调用了，有什么用呢？

我看源码 https://github.com/rime/librime/blob/236803406b2f26057ef5316d7de1c1b2cc434c5c/src/rime/candidate.h#L116-L150

好像只是在内部的 `CandidateList items_;` 尾部添加一个 cand 引用，但这个引用好像从不会调用

```c
  void Append(an<Candidate> item) {
    items_.push_back(item);
    if (quality() < item->quality())
      set_quality(item->quality());
  }
```

比方说 获得  text 也只是获取  `CandidateList items_;`  的（构造时添加的）第一个 cand 引用（而不是新加的最后一个）

```c
  const string& text() const {
    return text_.empty() && !items_.empty() ?
        items_.front()->text() : text_;
  }
```

获取 comment  也是如此

```c
  string comment() const {
    return comment_.empty() && !items_.empty() ?
        items_.front()->comment() : comment_;
  }
```

那样如果我在 lua filter 中遍历 cand 时遇到要修改 cand 的 text、comment 情况，是不是还是无法修改？

**Comment by shewer** [comment]
查一下 memory.cc   OnCommit() 
會展𨳡裡面 的 candidate  更新有需要update userdb 的字典

**Comment by LawssssCat** [comment]
> 查一下 memory.cc OnCommit() 會展𨳡裡面 的 candidate 更新有需要update userdb 的字典

是指这个吗？

https://github.com/rime/librime/blob/1c2644de2b026972dd80a3770b92d7194d523303/src/rime/gear/memory.cc#L103-L120

```c
void Memory::OnCommit(Context* ctx) {
  if (!user_dict_|| user_dict_->readonly())
    return;
  StartSession();
  CommitEntry commit_entry(this);
  for (auto& seg : ctx->composition()) {
    auto phrase = As<Phrase>(Candidate::GetGenuineCandidate(
            seg.GetSelectedCandidate()));
    bool recognized = Language::intelligible(phrase, this);
    if (recognized) {
      commit_entry.AppendPhrase(phrase);
    }
    if (!recognized || seg.status >= Segment::kConfirmed) {
      commit_entry.Save();
      commit_entry.Clear();
    }
  }
}
```

好像也只是调用了  GetGenuineCandidate 获取（构造时添加的）第一个 cand ？

```c
an<Candidate>
Candidate::GetGenuineCandidate(const an<Candidate>& cand) {
  auto uniquified = As<UniquifiedCandidate>(cand);
  return UnpackShadowCandidate(uniquified ? uniquified->items().front() : cand);
}
```
