### ISSUE TITLE
如何通过 lua_processor 发送任意按键或提交任意候选？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#21]
例如想要按 7 来发出 2，选第 2 个候选。因为可能需要动态判断，数字不固定，不能用方案配置的 key_binder 实现。

如果 lua_processor 不能发送任意按键（代码中也确实没有 `send` 这样的关键词），那么有没有函数来提交已生成的任意候选？

说到了候选，不知道函数 `get_selected_candidate` 的确切用法，随意讨论一下。

```lua
    if context:get_selected_candidate() then
      cand:get_genuine().comment = context:get_selected_candidate().text
    end
```

在 page_size 为 5 和 10 两种条件下测试。
结果是，除开第一页的边界情况外，每一页从第三个候选起，至下一页第二个候选，共计 page_size 个，其 comment 都是一样的，都是从上一页翻页过来之前被选中的候选的 text。
不知道这样的特性有什么应用场景？

**Comment by hchunhui** [comment]
> 例如想要按 7 来发出 2，选第 2 个候选。因为可能需要动态判断，数字不固定，不能用方案配置的 key_binder 实现。
> 
> 如果 lua_processor 不能发送任意按键（代码中也确实没有 `send` 这样的关键词），

是的，现在不行。原生的 `key_binder` 组件最后调用的应该是 [`Engine::ProcessKey()`](https://github.com/rime/librime/blob/3b5dbf61527cc128d482c4726017d1516d59c3d4/src/rime/engine.h#L25) ，但这个函数还没有绑定。

> 那么有没有函数来提交已生成的任意候选？

可参考 librime 里面的实现，然后翻译成 lua。可以参考 https://github.com/rime/librime/blob/3b5dbf61527cc128d482c4726017d1516d59c3d4/src/rime/gear/selector.cc#L180 。

> 
> 说到了候选，不知道函数 `get_selected_candidate` 的确切用法，随意讨论一下。
> 
> ```lua
>     if context:get_selected_candidate() then
>       cand:get_genuine().comment = context:get_selected_candidate().text
>     end
> ```
> 
> 在 page_size 为 5 和 10 两种条件下测试。
> 结果是，除开第一页的边界情况外，每一页从第三个候选起，至下一页第二个候选，共计 page_size 个，其 comment 都是一样的，都是从上一页翻页过来之前被选中的候选的 text。
> 不知道这样的特性有什么应用场景？

`get_selected_candidate` 应该就是得到当前选中的候选的意思吧，我没有试用过。
我认为上述代码只能体现 comment 赋值时选中的候选。之后通过翻页或者方向键虽选中了新的候选，但 comment 没有得到更新。

**Comment by Ace-Who** [comment]
> 可参考 librime 里面的实现，然后翻译成 lua。可以参考 https://github.com/rime/librime/blob/3b5dbf61527cc128d482c4726017d1516d59c3d4/src/rime/gear/selector.cc#L180 。

`selected_index` 只在 `segment` 里找到。
但用 `env.engine.segment.selected_index` 读不到，应该怎么写呢？

**Comment by hchunhui** [comment]
```lua
local ctx = env.engine.context
local comp = ctx.composition
local selected_index = comp:back().selected_index
```

**Comment by Ace-Who** [comment]
明白了，问题解决了，谢谢。
