### ISSUE TITLE
支持 lua 的 rime 发行版有哪些？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#22]
weasel 支持。trime 原版已知不支持，Linux 的从一个用户反馈来看也不支持。

**Comment by hchunhui** [comment]
我知道目前 rime 官方发行的 weasel 和 squirrel 的最新版二进制应该都支持 lua 。

其他 rime 发行版支持 lua 应该没有太大难度，改一改编译配置应该就行，只是现在还没有人推动。
特别是 Linux 上，要有人逐一联系各 Linux 发行版讨论如何打包，并修改打包配置。

---
在 [这里](https://github.com/hchunhui/build) 有我正在实验的 [AppImage](https://appimage.org/) 格式，带 lua 和 octagram 插件的 ibus-rime 打包脚本。
Linux 用户可以参考仓库中的 `build.sh` 自行编译，或者在 Release 页面下载 travis-ci 编译的二进制。

用法（实验品，后果自负）：
1. 删除系统自带 ibus-rime；
2. 为生成的 AppImage 文件加上可执行权限，双击安装；
3. 重新登录，在 ibus 配置界面加入新版的 rime 输入法。

**Comment by Ace-Who** [comment]
好的，谢谢。

**Comment by bj1949007** [comment]
trime 原版已支持
