### ISSUE TITLE
能获取前一次上屏的内容吗？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#23]
如题。

**Comment by hchunhui** [comment]
librime 里面有个专门的 `CommitHistory` 还没绑定，欢迎贡献。
也许也可以变通一下，如写一个 `processor` 自行跟踪。

**Comment by Ace-Who** [comment]
最近又想起这个问题了，用 `processor` 跟踪也不知道怎么做。我的理解是要判断按键是否触发上屏，但是这不可靠，因为有多个按键会上屏，同一个按键在不同情况下作用也不同，还有顶字上屏或自动上屏的情况，更无法通过按键来判断了。也没找到直接捕获上屏事件的方法。

**Comment by hchunhui** [comment]
正好，前一段时间为了解决云输入造词的问题，我新绑定了一些 notifer，其中包括在上屏之前的通知机制。这样应该也能解决你的需求。

复现上屏历史的 `translator` 的粗糙实现大概如下（要用最新的版本，可以在本项目的 ci 里面找到编好的 rime.dll）：
```lua
return {
   init = function (env)
      local context = env.engine.context
      env.hists = {}
      env.connection = context.commit_notifier:connect
      (function(ctx)
            table.insert(env.hists, ctx:get_commit_text())
      end)
   end,
   func = function (input, seg, env)
      if input == "hist" then
         for _, v in ipairs(env.hists) do
            yield(Candidate("history", seg.start, seg._end, v, "History"))
         end
      end
   end
}
```
`commit_notifier` 是在上屏前通知一次，可以如上用 `connect` 绑定一个回调。
`connect` 的返回值是一个 `connection` 对象，需要被 lua 这边持有（上面是通过赋值到 env 的一个成员中来实现），否则 lua 在 gc 的时候回调会断掉。

其他还绑定了 `select_notifier` `update_notifier` 等，可能也会派上用场，不过我暂时还没来得及研究它们的具体触发时机和用途。

**Comment by Ace-Who** [comment]
先简单依样画葫芦，成功在 `env.hists` 里记录到了上屏历史，不过算法服务崩溃了两次，`charset_filter` 也失效了。错误日志：

    E0407 01:11:07.750661 1786568 charset_filter.cc:104] charset parameter is unsupported by basic charset_filter

**Comment by Ace-Who** [comment]
更深入地运用了一下这个新特性，够用了。但是算法服务崩溃是周期性的，打不了多少字就崩溃一次。

**Comment by hchunhui** [comment]
有造成崩溃的例子吗，或者是崩溃日志？我在 Linux 平台下好像还蛮稳定。

`charset_filter` 失效是因为 ci 里面没有编除了 lua 之外的插件，与崩溃应该无关。

最早的时候 `translator` 和 `filter` 都是没有 `env` 参数的，那时候写的样例比现在会少一个参数。后来在加 `env` 时，了解到 lua 的函数在定义和调用的时候个数可以不一样，所以统一加到最后一个参数上，这样新旧之间就能兼容（有些样例因此也没有改过来）。在被纳入 rime 官方编译的时候，已经可以支持 `env`。

**Comment by Ace-Who** [comment]
错误日志里只有 `charset_filter` 那一条，这个和新写的一个 lua_filter 脚本都与崩溃无关，我在方案里去掉它们也会崩溃，旧的 lua 脚本有点多，还没排查过。

**Comment by Ace-Who** [comment]
不知道和我的 Windows 7 系统有没有关系，这个系统下之前就有个问题 https://github.com/rime/weasel/issues/447 。

**Comment by hchunhui** [comment]
试试把 notifier 置为空函数，看看是否崩溃，可以排除一下我新加的代码的问题。剩下可以看一下脚本对 `Context` 里面方法的调用，因为我发现有些接口只能在 `processor` 里面才能用，放到 `translator` 里面就会崩溃。同理在 notifier 里面也许也有类似的限制。

**Comment by Ace-Who** [comment]
我只使用旧的脚本里（没有 `notifier`），也会崩溃，现在正在排查旧的脚本，目前在方案里去掉了所有 lua 组件，正常打字挺久了，看来不会崩溃。

**Comment by lotem** [comment]
`connection` 在什麼時候斷開？會不會是callback先銷毀了而signal沒有斷開註冊到callback的連接。

**Comment by hchunhui** [comment]
没有显式的断开连接。我选用的是 `scoped_connection`，如果我没理解错的话，`scoped_connection` 是在对象销毁的时候自动断开 callback。代码中的 `scoped_connection` 对象生存期是由 lua gc 管理的，即只要 lua 这边一直持有，连接就不会被断开。比如赋值到 `env` 上，而 `env` 是在 `translator` 析构时才被销毁，此时应该才断开。

第二个问题很有启发，之前确实没有仔细分析 connection 和 callback 两者的生存期。不过我想了一下，觉得 callback 不会先于 `scoped_connection` 销毁。原因如下：

lua callback function 在 C++ 这边表现为 `LuaObj`，由 `shared_ptr` 管理（即 `an<LuaObj>`）。因为 `LuaObj` 在存活期间会向 lua 注册，所以不存在 `an<LuaObj>` 引用数未归零，`LuaObj` 却被 lua gc 销毁的情况。`an<LuaObj>` 对象通过这一行的 C++ lambda 表达式被 `scoped_connection` 持有：
https://github.com/hchunhui/librime-lua/blob/4163a6b6169535b365c67c78af7f8cec903d6e14/src/types.cc#L669
上面 capture list 中的 `o` 就是 lua callback。
所以，若 connection 不被销毁，则 callback 的引用数不会归零，callback 的生存期一定不会短于 connection。

**Comment by Ace-Who** [comment]
刚刚一次崩溃有日志了：

    E0408 23:28:22.459592 1783792 lua_gears.cc:15] LuaTranslation::Next error(5): error in __gc metamethod (bad argument #1 to '?' (struct LuaType<class boost::signals2::scoped_connection> expected, got __connection))

**Comment by hchunhui** [comment]
这个日志很关键啊，找到问题了。是我把 metatable 的名字写错了。内部使用这个名字作为类型检查的依据，当执行 gc 时因类型不匹配而报错崩溃。
另外我把原来画蛇添足的 `scoped_connection` 换回 `connection` 了，这样就不用再纠结 gc 的问题了。

**Comment by lotem** [comment]
讚！技術力一流。
啥時候再發新版本？

**Comment by Ace-Who** [comment]
谢谢，先关了，继续试用。希望能在正式版里用到。

**Comment by Lantaio** [comment]
请问各位大神，现在这个功能是不是已经实现了？如果我想知道刚上屏的内容是不是'.'（英文句号），if语句要怎么写？

**Comment by shewer** [comment]
https://github.com/hchunhui/librime-lua/wiki/Scripting#commithistory

**Comment by Lantaio** [comment]
十分感谢@shewer 的回应，上一个问题已经解决了，谢谢！不过又遇到最后一个问题，就是如何上屏'退格键'这种特殊按键？我已经知道普通的字符可以用`env.engine:commit_text('ABC')`上屏，但特殊字符wiki里找不到方法。如果有哪位大神知道的话，请指教，先谢了。

**Comment by shewer** [comment]
librime 只是把 commit 的text 送出去給 前端，就我使用經驗
前端把text 送到active window,   而text 中 容易接受的控制碼  '\t \r \b '

而active window 大概只剩terminal  可以處理 ansi code  "ESC["
print('abcd^[[0Gzzz')  -->  zzzdefg

**Comment by Lantaio** [comment]
再次感谢 @shewer 的解答。但是测试后发现不是我期望的结果。比如我写`env.engine:commit_text('\b')`，我是希望它会删除前一个已经上屏的字符，但在3个文本编辑器测试都没有实现预期的效果，却是上屏了一个表示退格的符号。我猜想可能用`commit_text()`方法不合适？

**Comment by Lantaio** [comment]
我的天，在cmd和PowerShell测试过，上面的写法是可以删除前一个已经上屏的字符，达到我所预期的效果的。然而在多数的软件里面却都是上屏1个表示退格的符号，而不是删除前一个字符。
另外，我的代码是写在processor的，所以我想到或者可以在满足条件时把传入的key_event参数（KeyEvent对象）的keycode属性值替换为退格键。但测试过好像改不了，难道这个keycode属性值是只读的？

**Comment by Lantaio** [comment]
这两天学习了一下这个仓库的示例，折腾出下面这个函数。虽然输出和没有执行这个函数一样（也就是没有达到预期效果），但感觉离真理越来越接近了，还请各位大神帮忙看看问题出在哪里？想实现的功能是当满足条件时就发送一个退格键。函数代码如下：

**Comment by Lantaio** [comment]
这两天学习了一下这个仓库的示例，折腾出下面这个函数。虽然输出和没有执行这个函数一样（也就是没有达到预期效果），但感觉离真理越来越接近了，还请各位大神帮忙看看问题出在哪里？想实现的功能是当满足条件时就发送一个退格键。函数代码如下：
``` Lua
local function p(key, env)
	if 满足某个条件 then
		key_bs = KeyEvent('BackSpace')  -- BackSpace / \b
		p_bs = Component.Processor(env.engine, "", "ascii_composer"):process_key_event(key_bs)  -- ascii_composer / express_editor
	end
	return 2 -- kNoop
end
```
这里有几个疑问：
1是`Processor`不是`Component`的方法吗？如果是方法的话，为什么是用'.'连接而不是用':'连接？不过我2种都试过，都不行。
2是`KeyEvent`里面的参数是`'BackSpace'`吗？我试过用`'\b'`也不行。
3是`Processor`方法的第3个参数可以用`“ascii_composer"`吗？还是要用`”express_editor"`来处理退格键？我的理解是`“ascii_composer"`处方也可以处理退格键的，我就当作是在英文模式下输入1个退格键，是由这个处方来处理的吧？不过也是2种都试过，都不行。
综上所述，还请各位大神帮忙看看问题出在哪里？感觉这个方向是对头的啊。求 @shewer @hchunhui 大神指点迷津，折腾了2个通宵了。

**Comment by Lantaio** [comment]
这两天学习了一下这个仓库的示例，折腾出下面这个函数。虽然输出和没有执行这个函数一样（也就是没有达到预期效果），但感觉离真理越来越接近了，还请各位大神帮忙看看问题出在哪里？想实现的功能是当满足条件时就发送一个退格键。函数代码如下：
``` Lua
local function p(key, env)
	if 满足某个条件 then
		key_bs = KeyEvent('BackSpace')  -- BackSpace / \b
		p_bs = Component.Processor(env.engine, "", "ascii_composer"):process_key_event(key_bs)  -- ascii_composer / express_editor
	end
	return 2 -- kNoop
end
```
这里有几个疑问：
1是`Processor`不是`Component`的方法吗？如果是方法的话，为什么是用'.'连接而不是用':'连接？不过我2种都试过，都不行。
2是`KeyEvent`里面的参数是`'BackSpace'`吗？我试过用`'\b'`也不行。
3是`Processor`方法的第3个参数可以用`“ascii_composer"`吗？还是要用`”express_editor"`来处理退格键？我的理解是`“ascii_composer"`处方也可以处理退格键的，我就当作是在英文模式下输入1个退格键，是由这个处方来处理的吧？不过也是2种都试过，都不行。
综上所述，还请各位大神帮忙看看问题出在哪里？感觉这个方向是对头的啊。求 @shewer @hchunhui 大神指点迷津，折腾了2个通宵了。
