### ISSUE TITLE
How do I make a global variable accessible from multiple scripts?

### ISSUE THREAD

**Issue by scorpjke** [hchunhui/librime-lua#239]
I tried using "env", for example I write env.x = 5. But if I check "env.x" in another script, it's nil. So how do I make truly global variables?

I need this because I've created a filter and a translator and they must work together to achieve the result.

**Comment by shewer** [comment]
https://github.com/shewer/librime-lua/blob/e587aef46c75cab00f73e7cea49011e0b1bc4d43/src/lua_gears.h#L76
env  is member (LuaObj) of instance

put in  rime.lua  
```lua
x=5

xxx_filter = require('....')
xxx_tran= require (...)


```
