### ISSUE TITLE
fcitx-rime如何使用lua插件

### ISSUE THREAD

**Issue by f4nyc** [hchunhui/librime-lua#24]
按照Readme从源码编译，/usr/lib中新增librime-lua.so，试用   - lua_translator@date_translator
但出现报错`E1208 00:16:36.506965 15620 engine.cc:349] error creating translator: 'lua_translator'`

**Comment by hchunhui** [comment]
fcitx-rime 尚不支持动态加载 librime 插件（如 `librime-lua.so`）。为了使用 lua，只能用 merged 模式编译。

具体方法是加入本项目代码后，在 librime 根目录下运行：
```
make merged-plugins
```
此时不会生成  `librime-lua.so` ，librime 的代码和本项目的代码都会编译进 `librime.so' 中。经安装后，fcitx-rime 即可使用 lua。
