### ISSUE TITLE
怎么让luafilter识别翻译器来源？或者匹配翻译器的tag

### ISSUE THREAD

**Issue by abcdefg233** [hchunhui/librime-lua#245]
失败案例：
![image](https://user-images.githubusercontent.com/32760059/235196045-3c7adfef-7bb8-4728-b6fe-9d54abe7ca0e.png)
![image](https://user-images.githubusercontent.com/32760059/235196095-fb793956-0ba4-490a-b016-feb0d583f121.png)
![image](https://user-images.githubusercontent.com/32760059/235196154-7553bd38-38b8-4344-b421-847047512da2.png)

**Comment by oniondelta** [comment]
感覺案例 tag 的有點奇怪！？

schema：

```yaml
engine:
  filters:
    - lua_filter@count_filter
  segmentors:
    - affix_segmentor@ts_en

count_filter:
  tags: [ ts_en ]

ts_en:
  tag: ts_en

```

用 lua tags_match 的解法：

https://github.com/hchunhui/librime-lua/pull/131

**Comment by oniondelta** [comment]
感覺 tag 的有點怪！？

```yaml
engine:
  segmentors:
#    - affix_segmentor@ts_en  # 併在 abc 一般輸入，可不用

count_filter:
  tags: [ ts_en ]

abc_segmentor:
  extra_tags:
    - ts_en

ts_en:
  tag: ts_en

```

或是純用 lua 的 tags_match 功能實現：https://github.com/hchunhui/librime-lua/pull/131

**Comment by shewer** [comment]
針對 單個 translator 處理，或許直接在 translator  中處理

```lua

tran_filter={}
function tran_filter.init(env)
  env.tran= Component.Translator(env.engine, "", "table_translator@ts_en")
end
function tran_filter.fini(env)
end
function tran_filter.func(input,seg,env)
  local t = env.tran:query(input, seg)
  for cand in t:iter() do
     yield( 
         cand:to_shadow_cand("Zen",cand.text, "英文") )
  end
end
```

**Comment by shewer** [comment]
直接委任 function  yield(cand)
```lua

tran_filter={}
function tran_filter.filter1(...)
    local tran,ct,cc = ...
   for cand in  tran:iter() do
      yield( cand:to_shadown_candidate( ct, cand.text, cc) )
  end
end

function tran_filter.init(env)
  env.tran= Component.Translator(env.engine, "", "table_translator@ts_en")
end
function tran_filter.fini(env)
end
function tran_filter.func(input, seg, env)
  local t = env:tran:query(input, seg)
  tran_filter.filter1(t, "Zen", "英文")
end
```
使用 Translation 可以拆分複雜處理程序
```lua

tran_filter={}
function tran_filter.filter1(tran,...)
    local ct,cc = ...
   for cand in tran:iter() do
      yield( cand:to_shadown_candidate( ct, cand.text, cc) )
  end
end

function tran_filter.init(env)
  env.tran= Component.Translator(env.engine, "", "table_translator@ts_en")
end
function tran_filter.fini(env)
end
function tran_filter.func(input, seg, env)
  local t = env:tran:query(input, seg)
  t = Translation( tran_filter.filter1, t , "Zen", "英文")
  --t = Translation( tran_filter.filter2, t,....) 
  for cand in t:iter() do
      yield(cand)
  end
```

**Comment by abcdefg233** [comment]
> 直接委任 function yield(cand)
> 
> ```lua
> tran_filter={}
> function tran_filter.filter1(...)
>     local tran,ct,cc = ...
>    for cand in  tran:iter() do
>       yield( cand:to_shadown_candidate( ct, cand.text, cc) )
>   end
> end
> 
> function tran_filter.init(env)
>   env.tran= Component.Translator(env.engine, "", "table_translator@ts_en")
> end
> function tran_filter.fini(env)
> end
> function tran_filter.func(input, seg, env)
>   local t = env:tran:query(input, seg)
>   tran_filter.filter1(t, "Zen", "英文")
> end
> ```
> 
> 使用 Translation 可以拆分複雜處理程序
> 
> ```lua
> tran_filter={}
> function tran_filter.filter1(tran,...)
>     local ct,cc = ...
>    for cand in tran:iter() do
>       yield( cand:to_shadown_candidate( ct, cand.text, cc) )
>   end
> end
> 
> function tran_filter.init(env)
>   env.tran= Component.Translator(env.engine, "", "table_translator@ts_en")
> end
> function tran_filter.fini(env)
> end
> function tran_filter.func(input, seg, env)
>   local t = env:tran:query(input, seg)
>   t = Translation( tran_filter.filter1, t , "Zen", "英文")
>   --t = Translation( tran_filter.filter2, t,....) 
>   for cand in t:iter() do
>       yield(cand)
>   end
> ```

如何在方案中调用这些代码？

**Comment by shewer** [comment]
把 table_translator@ts_en 換成  lua_translator@tran_filter@ts_en
    ( @  [lua function or table]  @  [name_space])

**Comment by abcdefg233** [comment]
> 把 table_translator@ts_en 換成 lua_translator@tran_filter@ts_en ( @ [lua function or table] @ [name_space])
> 
> 把上面 script 存檔 (ex : lua/tran_filter.lua) 上面 的腳本是直接寫在 rime.lua 用的是全域變數 記得把 table 改成 local table and return table
> 
> ```lua
> local tran_filter={}  -- 改成 區域變數
> .......
> 
> return tran_filter   --  require 時 return  tran_filter
> ```
> 
> 手動載入 在rime.lua 中加入
> 
> ```lua
> tran_filter = require("tran_filter")
> ```
> 
> 自動載入 不用在rime.lua 加require lua_translator@*tran_filter@ts_en
 
![CFS8M D{O)Q5XU) YEKAMGY](https://user-images.githubusercontent.com/32760059/235300830-4049d1d8-209e-4249-9738-f9d0bd696a7b.png)
![SCZ09DIOLCA74_KCKOS6{Y6](https://user-images.githubusercontent.com/32760059/235300832-8b9ba4ae-4716-4064-8bad-e74ddc2f08cd.png)
![RCNXI}EK6`6MAD6OV3YP%@5](https://user-images.githubusercontent.com/32760059/235300833-7d77bb70-3e2a-4cbf-8eb2-c98d331c8827.png)
![image](https://user-images.githubusercontent.com/32760059/235300886-53a7b4cf-5538-40d7-950e-2f140c8b37cd.png)
不生效，

 
可以演示一下，如何在rime.lua内直接让这个luafilter只匹配"ts_en"这个特定tag吗？
```lua
--[[＝＝＝＝＝＝运行逻辑＝＝＝＝＝＝＝＝
１定义计数变量a
２在词条中查找"[a-z]"
　1没找到，就直接返回候选
　2找到了，就判断a是否小于通过阈值:1
　　I 小于则允许候选通过，然后根据词条长度计数，词条越短计数越多，防止过短词条淤积。
　　II大于则不再允许通过。
结束
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝--]]

function en_count_filter(input)
	local a = 0
	for cand in input:iter() do
		if(not string.find(cand.comment,"[a-z]"))then yield(cand) else
		if(a<1) then yield(cand) a = a+4/(string.len(cand.text)) else
end end end end

```

**Comment by shewer** [comment]
to_shadown_candidate   --> shadow  多個n   log 應該有錯誤訊息
這是 lua_translator  , 直接在 translator 內部 轉置 translation
ts_en 是 name_space 不是tag

這個 lua_translation   只是在 table_translator@ts_en 加上一層，  目的是爲了
在 table_translator@ts_en  輸出的 translation  後 ，再加工 translation

**Comment by abcdefg233** [comment]
> to_shadown_candidate --> shadow 多個n log 應該有錯誤訊息 這是 lua_translator , 直接在 translator 內部 轉置 translation ts_en 是 name_space 不是tag
> 
> 這個 lua_translation 只是在 table_translator@ts_en 加上一層， 目的是爲了 在 table_translator@ts_en 輸出的 translation 後 ，再加工 translation

可以让lua filter匹配特定tag吗？因为这样似乎效果更好

**Comment by shewer** [comment]
不知道從何說起， segment.tags 必須保證只有唯一 一個 tags
如果 在處理的 segment  中有  多個tag     
lua_filter  func(inp,env)  <---- inp : translation   是混 著其他 tags  的 translation

假設 你的 filter 想要針對一個tag 用上法
假設 你的 filter 想要針對多個指定 tag   處理 必須保保證 segment tags  只能有容許tags 

如果你  只想處理  tag :  a b
 但是這 translation 是混着  abc a b  

你可以試着用 recognizer 類似機制  segment 只有 a     或 只有b
那麼  tags_match  or  yaml tags: [a , b] 
才可保證  filter  可以專用

**Comment by abcdefg233** [comment]
> 不知道從何說起， segment.tags 必須保證只有唯一 一個 tags 如果 在處理的 segment 中有 多個tag lua_filter func(inp,env) <---- inp : translation 是混 著其他 tags 的 translation
> 
> 假設 你的 filter 想要針對一個tag 用上法 假設 你的 filter 想要針對多個指定 tag 處理 必須保保證 segment tags 只能有容許tags
> 
> 如果你 只想處理 tag : a b 但是這 translation 是混着 abc a b 就會連 abc 也 被lua_filter 處理
> 
> 你可以試着用 recognizer 類似機制 segment 只有 a 或 只有b 那麼 tags_match or yaml tags: [a , b] 才可保證 filter 可以專用

我看不懂任何完整形式的 lua 组件和 tags_match，流行的 lua 组件也少采用完整形式，而且我也找不到采用了 tags_match 的 lua filter。
但是我知道lua filter不能像正常filter一样通过在方案中设置tags来针对特定tag，目前我唯一发现的可行方案是通过在词库中添加前缀，使 lua filter 匹配这些前缀的同时返回无前缀的候选，以此保证 lua filter 间不互相干扰
![image](https://user-images.githubusercontent.com/32760059/235306569-a7b82b82-df7c-4ebd-b138-e1c5d29e0a45.png)

如果 lua filter 能像普通的 filter 一样匹配 tag 就好了
![image](https://user-images.githubusercontent.com/32760059/235306767-13cf8e44-5c92-474f-ba42-1af5092d7299.png)

**Comment by shewer** [comment]
lua_filter 是 rime filte 子類別  , 井 沒有你所說的"如果 lua filter 能像普通的 filter 一样匹配 tag 就好了"

你可能理解錯誤了

tags :  的 工作原理 請 查看  src/rime/gear/filter_commons.h cc

**Comment by abcdefg233** [comment]
![image](https://user-images.githubusercontent.com/32760059/235307980-9b83ae39-e635-4c6c-8e41-7f4ef891df93.png)

lua filter 如此配置的话，只要编码符合recognizer/patterns，内对tags匹配的定义，就会转换 

![image](https://user-images.githubusercontent.com/32760059/235308085-74182c09-962f-4f3a-a999-fbac2ccfa549.png)

lua filter 如此配置的话，就会与abc tag一同转换，因此 lua filter 不能像普通的 filter 一样匹配 tag

**Comment by shewer** [comment]
affix_segment@ts_en  <---   產生 一個 affix_segment  設定參數 自 ts_en  取得

lua_filter@count_filter <----  產生一個 lua_filter   lua script name count_filter( func or table)

table_translator@ts_en < --  產生一個 table_translator 設定參數自 ts_en 取得

abc_segmentor  <-   產生一個 abc_segmentor 設定參數 自 abc_segmentor 取得
   abc_segment 僅可設定 extra_tags ,    只要 segment  有abc  tag   就一定有 extra_tags 中的tag

engine/translators:
   - table_translator@ts_en   table_translator
ts_en:
   tag: abc     

table_translator@ts_en  產生 table_translator 參數取自 ts_en   tag 為abc

translator 傳入參數  context.input , segment   
   translator  自segment  檢查 是否有 abc :    有則工作  , 無則不理會

**Comment by oniondelta** [comment]
之前以下 tags 皆沒問題！都可限定 filter 範圍。
但沒像該帖，合併兩個 translator 再針對其一作針對性的 filter。

```yaml
engine:
  filters:
    - lua_filter@en_sort_filter
    - simplifier@emoji_switch

en_sort_filter:
  tags: [ easy_en ]

emoji_switch:
  opencc_config: emoji_t.json
  option_name: emoji_segestion
  tags: [ abc ]
```

改一個方案作測試，發現：

不管附加方案（例：easy_en）「extra_tags:」合併到 abc
或是「extra_tags:」合併兩個附加方案，都用\`[a-z]調出，

皆無法用「tags: 」作針對性 filter，全部都會作用，
且不管是 lua filter 或是原生 opencc 掛接皆如此。

這邊的理解是：
segmentor 是辨認` input 原始輸入`為依據作用，
如下方去限定，ts_en 該方案會作用的時機，

```yaml
recognizer:
  patterns:
    ts_en: "^`[a-z]'?$"
```
tag 理解是只給予名稱作接入調用，
tags 實際針對的是 segmentor 辨認的` input 原始輸入`，如：recognizer/patterns 的項目，作為限定範圍。

**Comment by shewer** [comment]
可以使用 cand.type
type start _end quality  在 class candidate  基類中
shadow phrase simple可以修改都可以
整個librime src中 有用 cand.type  參考的不多 大多是 user_table table

**Comment by abcdefg233** [comment]
![image](https://user-images.githubusercontent.com/32760059/235425552-3a96a2f2-eda5-4b0e-bc1e-1f6ce260350c.png)
![image](https://user-images.githubusercontent.com/32760059/235425727-8f9c9386-85c8-4054-ac62-2526a2a53d43.png)
  
cand type 区分不了同type候选的翻译器来源

**Comment by shewer** [comment]
replace  table_translator@ts_en ----> lua_translator@*ts_en@ts_en  
```lua
-- lua/ts_en.lua
-- schema.yaml   replace  engine/translators/@?:   lua_translator@*ts_en@ts_en

return function (inp, seg, env) 
  env.tran =  env.tran or Component.Translator(env.engine, "","table_translator@ts_en"

  for cand in env.tran:query(inp,seg):iter() do
     cand.type= "A_" .. cand.type  -- <   A_table  A_user_table
     yield( cand)
  end
end
```

**Comment by abcdefg233** [comment]
> lua_translator@*ts_en@ts_en

感谢！现在可以通过type区分翻译器了！
![image](https://user-images.githubusercontent.com/32760059/235428315-cc21b922-38ad-4c9f-94be-ced598885d30.png)

**Comment by abcdefg233** [comment]
> replace table_translator@ts_en ----> lua_translator@*ts_en@ts_en
> 
> ```lua
> -- lua/ts_en.lua
> -- schema.yaml   replace  engine/translators/@?:   lua_translator@*ts_en@ts_en
> 
> return function (inp, seg, env) 
>   env.tran =  env.tran or Component.Translator(env.engine, "","table_translator@ts_en"
> 
>   for cand in env.tran:query(inp,seg):iter() do
>      cand.type= "A_" .. cand.type  -- <   A_table  A_user_table
>      yield( cand)
>   end
> end
> ```

这个写法只能用于新版librime，如何转写成支持librime1.5.3的版本？

**Comment by shewer** [comment]
查一下 librime-lua 版本  是否支援 Memory( function) 
if Memory then 
   return "ok"
end
怎麼用 可以參考 example

**Comment by abcdefg233** [comment]
![image](https://user-images.githubusercontent.com/32760059/235591802-a5ceec7b-3dad-4860-960e-8f6e9eeb15d0.png)

![image](https://user-images.githubusercontent.com/32760059/235591984-dbe3004b-b299-482f-a842-4ab00ac2de7d.png)

哪些地方使用了新版Rime Lua的接口？旧版本能实现相同效果吗？

**Comment by shewer** [comment]
https://github.com/hchunhui/librime-lua/issues/207

**Comment by abcdefg233** [comment]
> #207
旧版没有component所以需要模拟一个吗？
![image](https://user-images.githubusercontent.com/32760059/235598001-45fedb91-fd9f-498a-ab86-9162277e11f8.png)

**Comment by abcdefg233** [comment]
我在Android上使用的Rime是中文输入法（同文无障碍），他的librime lua版本较低，使用不了component接口，但是我在example中看到了expand_translator，他似乎是用memory接口来输出遍历词库的，请问用component接口的lua translator，可以转写为使用memory接口的lua translator吗？

>```lua
>--rime.lua
>function cp(inp, seg, env)
>	env.tran =  Component.Translator(env.engine, "","table_translator@cp")
>	for cand in env.tran:query(inp,seg):iter() do
>	cand.comment="『自定义』" cand.type="cp" yield(cand)
>end end
> ```

lua_translator@cp，作用是将table_translator@cp的提示码改为『自定义』，在旧版librime lua能实现吗？

**Comment by mokapsing** [comment]
> 我在Android上使用的Rime是中文输入法（同文无障碍），他的librime lua版本较低，使用不了component接口，但是我在example中看到了expand_translator，他似乎是用memory接口来输出遍历词库的，请问用component接口的lua translator，可以转写为使用memory接口的lua translator吗？
> 
> > ```lua
> > --rime.lua
> > function cp(inp, seg, env)
> >   env.tran =  Component.Translator(env.engine, "","table_translator@cp")
> >   for cand in env.tran:query(inp,seg):iter() do
> >   cand.comment="『自定义』" cand.type="cp" yield(cand)
> > end end
> > ```
> 
> lua_translator@cp，作用是将table_translator@cp中所有候选的提示码改为『自定义』，在旧版librime lua能实现吗？

应该不行吧，大家一起劝作者更新下插件吧
