### ISSUE TITLE
如何识别不可见的繁体生僻字

### ISSUE THREAD

**Issue by boomker** [hchunhui/librime-lua#247]
我写了一个lua 脚本来让单字全码唯一时自动顶功上屏,  但是发现,  有个别繁体生僻字是在输入法候选菜单UI里是不可见的,  我的目的是脚本判断如果是这些不可见的生僻字, 那么就移除. 具体问题看下图效果
<img width="340" alt="image" src="https://user-images.githubusercontent.com/19751472/236195495-78b11d29-a92c-42b6-ac9e-87bdd6465f43.png">

lua 脚本 输出的日志里可以看到有两个候选项 “朝”, 和 “𥖨”,  但是正常输入时却无法看到 

Candidate 对象是否有什么属性或方法可以识别这种不可见的字,  希望大佬可以指点一二, 感谢

**Comment by mokapsing** [comment]
开字符集过滤了吧

**Comment by boomker** [comment]
> 开字符集过滤了吧

是的,  额, 开了过滤为什么会 出现在 日志里?

**Comment by mokapsing** [comment]
时机不同吧，你lua是挂在最后面吗

**Comment by boomker** [comment]
> 时机不同吧，你lua是挂在最后面吗

嗯嗯, 之前字符集过滤写在了 custom 里了,  其他的 lua 挂在 schema 里了, 调整了顺序好了,  感谢您的解答
