### ISSUE TITLE
组件间如何传值 &&  leveldb 文档缺失

### ISSUE THREAD

**Issue by boomker** [hchunhui/librime-lua#250]
多个 lua  脚本间如何传值, 排除通过 lua 导出功能, 有没有其他最佳实践, 我想到了 leveldb, 但是 wiki 里没有相关详细文档.
目前从仓库示例脚本看到有这样几个方法: open, load, update, 其他方法是否还有呢?

**Comment by shewer** [comment]
使用全域变数
env.engine.context:get_property(key)  return string 
set_property(key, string)
