### ISSUE TITLE
DictEntry.custom_code 赋值时报错

### ISSUE THREAD

**Issue by ksqsf** [hchunhui/librime-lua#253]
```
E20230714 22:03:50.836462  7028 types.cc:1488] LuaMemory::Memorize error(2): bad argument #2 to '?' (struct LuaType<struct rime::DictEntry &> expected)
E20230714 22:03:52.743438  7028 types.cc:1488] LuaMemory::Memorize error(2): bad argument #2 to '?' (struct LuaType<struct rime::DictEntry &> expected)
```

不是很理解这个报错到底是在说什么…… 

相关代码：

```lua
   env.mem:memorize(function(commit)
         for i, entry in ipairs(commit:get()) do
            entry.custom_code = ''  -- 这一行报错
         end
   end)
```

**Comment by shewer** [comment]
你想要做什么，
按范例用有问题吗 
https://github.com/hchunhui/librime-lua/blob/master/sample/lua/expand_translator.lua  



commit:get()  会得到 vector<const DictEntry>
entry 会不会是不可改变


https://github.com/hchunhui/librime-lua/blob/c985eb399d63c491c6e03fa1651ddb59e485c04a/src/types.cc#L1359-L1361

**Comment by ksqsf** [comment]
我的需求是把 table translator 得到的 commit entry 更新到 script translator 的 user dict 里，这里是想修改记录的 code。

这里已经写清楚是 const 了，那我明白这是不能做到的了。
