### ISSUE TITLE
如何在translator解析前拦截并处理key_event?

### ISSUE THREAD

**Issue by Gaeric** [hchunhui/librime-lua#259]
我希望使用lua实现一个aeuio选重的功能：
在某些特定的条件下，使用aeuio选择第1/2/3/4/5个候选项

方案中的processors如下：
``` yaml
  processors:
    - ascii_composer
    - lua_processor@aeuio_key_binder
    - recognizer
```
translators如下：
``` yaml
  translators:
    - lua_translator@demo_translator
    - punct_translator
    - reverse_lookup_translator
    - table_translator
```
我写了一个aeuio_key_binder和demo_translator
``` lua
function aeuio_key_binder(key_event, env)
   log.info("aeuio key binder load")
   return 2
end

function demo_translator()
   log.info("demo translator load")
end
```
观察aeuio_key_binder会执行两遍，应该是按键触发一次，释放按键触发一次，
然而demo_translator会在两次触发中间插入执行，
日志截取如下：

I20230806 17:52:28.309713 53722 types.cc:786] the input string is yx
I20230806 17:52:28.404662 53722 types.cc:786] aeuio key binder load
I20230806 17:52:28.404706 53722 types.cc:786] the input string is yx
I20230806 17:52:28.404742 53722 types.cc:786] demo translator load
I20230806 17:52:28.432440 53722 types.cc:786] aeuio key binder load

因此我无法通过aeuio_key_binder去实现目的，请问有没有什么建议？

**Comment by shewer** [comment]
麻煩的是  aeiou 何時才要改成  12345 
has_menu 時  aeiou  是否還是 translator  的字根

候選  數字上屏 看一下 selector.cc 的code 
https://github.com/rime/librime/blob/97af61b2bfb322416d329a14f1bb7b9177d535ba/src/rime/gear/selector.cc#L255

可以用 lua  按其程序 處理即可，
或是用  把 aeiou 
 改成 12345  的 KeyEvent   用 engine.sendkey ( 再送一次）
```lua
    local select_key= {a=1,e=2, i=3,o=4,u=5}
    local    k = select_key[key:repr()]
    if   k then
         return  env.engine:send_key( KeyEvent( k) )
    end
     return 2
```
一個鍵   會 產生   按下  和 release  所以是 正常的
 把  key:repr() （字串）   放入 log 看 看

**Comment by Gaeric** [comment]
感谢您的回复。是我对当前字符串input的理解出现了偏差，通过上面的这种方式应当可以实现我需要的功能，具体的细节我在自己学习一下。
