### ISSUE TITLE
怎么搞？

### ISSUE THREAD

**Issue by 4SM** [hchunhui/librime-lua#26]
看不懂啊。可以直白一些吗？例如一步一步的操作说明书？😅

**Comment by hchunhui** [comment]
是不清楚如何使用，还是不清楚如何编译本项目？此两者分别在 README 中的 Usage 和 Build 之中，都是有效的、一步一步的说明。

本项目的功能是，在 rime 输入法启动的时候读取用户配置目录下的 `rime.lua` 文件，然后向 rime 注册此文件中定义的新组件（比如可以输入日期的翻译器）。这些新组件将在输入法配方中被调用。

如果是使用：
1. 首先要准备好 `rime.lua` 文件，如果是这部分不懂请参看本项目的 `sample` 目录，或者复制第三方的文件。
2. 然后在要增强的输入法的配方文件中引用，才能真正看到效果。如果是这部分看不懂请参看 rime 的[定制指南](https://github.com/rime/home/wiki/CustomizationGuide)。

另请确保使用的是 rime 官方编译的最新版本的小狼毫或鼠须管，其他的发行版不一定支持。

**Comment by 4SM** [comment]
> 
> 
> 是不清楚如何使用，还是不清楚如何编译本项目？此两者分别在 README 中的 Usage 和 Build 之中，都是有效的、一步一步的说明。
> 
> 本项目的功能是，在 rime 输入法启动的时候读取用户配置目录下的 `rime.lua` 文件，然后向 rime 注册此文件中定义的新组件（比如可以输入日期的翻译器）。这些新组件将在输入法配方中被调用。
> 
> 如果是使用：
> 
>     1. 首先要准备好 `rime.lua` 文件，如果是这部分不懂请参看本项目的 `sample` 目录，或者复制第三方的文件。
> 
>     2. 然后在要增强的输入法的配方文件中引用，才能真正看到效果。如果是这部分看不懂请参看 rime 的[定制指南](https://github.com/rime/home/wiki/CustomizationGuide)。
> 
> 
> 另请确保使用的是 rime 官方编译的最新版本的小狼毫或鼠须管，其他的发行版不一定支持。



> 
> 
> 是不清楚如何使用，还是不清楚如何编译本项目？此两者分别在 README 中的 Usage 和 Build 之中，都是有效的、一步一步的说明。
> 
> 本项目的功能是，在 rime 输入法启动的时候读取用户配置目录下的 `rime.lua` 文件，然后向 rime 注册此文件中定义的新组件（比如可以输入日期的翻译器）。这些新组件将在输入法配方中被调用。
> 
> 如果是使用：
> 
>     1. 首先要准备好 `rime.lua` 文件，如果是这部分不懂请参看本项目的 `sample` 目录，或者复制第三方的文件。
> 
>     2. 然后在要增强的输入法的配方文件中引用，才能真正看到效果。如果是这部分看不懂请参看 rime 的[定制指南](https://github.com/rime/home/wiki/CustomizationGuide)。
> 
> 
> 另请确保使用的是 rime 官方编译的最新版本的小狼毫或鼠须管，其他的发行版不一定支持。

谢谢耐心解答。我晚上再摸索一下😅
