### ISSUE TITLE
如何获取特定 segmentor 分割后的 input？

### ISSUE THREAD

**Issue by abcdefg233** [hchunhui/librime-lua#262]
对于候选 "你好"
编码是："ni hao^a"
有三种获取编码的方式：
```lua
env.engine.context.input=="nihaoa"
env.engine.context.composition:toSegmentation().input=="nihao"
env.engine.context.composition:back():get_candidate_at(0).preedit=="ni hao"
```
前两种无法获取分割，第三种在没有候选的情况下无效。
请问有没有办法在无候选的情况下获取特定 segmentor 分割后 input？

**Comment by shewer** [comment]
沒辦法在無候選時

"nihao"   是在 script_translation  內部直接處理的



你的 segments   可能只有一個   segment
nihaoa  實際上是在 script_translator 產生的 script_translation
在處理的

ctx:get_selected_candidate() 須在 完成 Engine::Compose()  後，也就是   lua_processor 中 且 ctx:has_menu()   才可以取得
```lua 
--env.engine.context.composition:back():get_candidate_at(0).preedit=="ni hao"
--  get_candidate_at() 不保證cand  != nil    
--  nil.preedit    ***** runtime error     
--   

  if ctx:has_menu() then
     local cand = ctx.composition:back():get_candidate_at(n) 
     if cand  and preedit == "ni hao" then 
     end
  end
```

另一個是由 lua_filter 去檢查 所有 translators 產生的 cand 
   preedit
``` lua 
-- lua_filter

function func(tran, env)
    for cand in tran:iter() do 
        if cand.preedit == "ni hao"  then 
        else
            yield(cand)
        end
    end
end

```

**Comment by shewer** [comment]
> 那看来是我理解错了，那有没有办法手动设置cand的特定分割？ 比如：
> 
> * 编码: nihao	wode
> * 候选: 你好	我的
> * 分割: ni hao	wo de
> 
> 请问该怎么做才能 用 lua_translator yield 出一个候选: "你好"，并且编码分割为 "ni hao"？
好像沒什麼必要，  script_translator  有斷詞設定 " ' " ,  nihaowode    就已是 "ni hao wo de"  且包含簡拼 還有智能學習,每次commit 都會調整權重，打久了命中率就會提高

下面都是 script_translator 自己完成的
nhwd   -> n h w d    
nihaowode --> ni hao wo de

**Comment by shewer** [comment]
> 碰到 [aeiou] 等想要的特殊條件，後面硬加入分節符號呢？
> 
> ```lua
>     if 分割條件 then
>       code = 加入分節符號後的編碼
>       context.input = code
>     end
> ```
> 
> 之前主方案為26鍵形碼，掛接42鍵注音去反查， 少鍵掛多鍵副方案，在選字和游標切分上，會有超多問題！ 尤其某些狀態下，選字後會跳回主方案， 以硬加前綴方式解決！
> 
> ```lua
> context.input = "';" .. new_c_input
> ```
> 
> 雖然目前還是有彆扭處，尤其某些狀況下用強迫上屏，會有記憶方面問題
> 
> https://github.com/oniondelta/Onion_Rime_Files/blob/main/allfiles/lua/processor_zhuyin_space.lua#L105

我是用 "P" 蜀發 pinyin 副字典
發現一個現象    default.yaml 中的recognizer 有  email   upacase 
都有     數字  ,   使用 副字典時，  容易被 upcase 截糊 (tag: upcase)
大概瞭解 ，為何在  caret_pos 位移後 無法選字的問題了


我在想 ，你是不是可以用  component  selector  來 處理 select candidate
```
local M={}
function M.init(env)
    env.select = Component.Processor(env.engine, "processor", 'selector")
end

function M.func(key, env)
    ......
    --[[
       engine:process_key( KeyEvent) return   true false
       env.select:process_key_event(KeyEvent)  return 0 1 2   (Rejected Accepted, Noop)
    --]]
    if key_num then
        --  如果是 數字  交給 env.select 處理 候選選字
        --  另一方法是用  local res = engine:process_key( KeyEvent(key_num)) ,  因爲是在 engine/processors 中再跑一遍  怕在 selector 前被其他processor rejected or accepted
        -- 方法一:
        local res =  env.select:process_key_event( KeyEvent( key_num))
        if res == 1 then return 1 end    -- Accepted
         --  方法二:  
        if env.engine:process_key( KeyEvent(key_num)) then
            return 1
        end
    elseif 
        .....
    end
end
```

**Comment by oniondelta** [comment]
26鍵形碼，掛接42鍵注音去反查，輸入碼如果有主方案沒有的鍵位，選字後會跳回主方案！
如果都是主方案有的鍵位，就沒問題！
default.yaml 中的 recognizer 問題，記得之前試時有踩到，但有排除！

之前有幾個思路：
①反查不用 rime 去掛，直接全用 lua 實現！（感覺 translators 和 processors 兩者都要寫）
②找出有半上屏狀態，不直接上屏的方法，
後來寫到茫茫然，問題有解決，雖有bug，就沒試了XD

**Comment by oniondelta** [comment]
感謝 shewer，這邊有得再研究了！😄
