### ISSUE TITLE
engine.active_engine 有什么使用场景？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#27]
内容太多了，找了一个，闲来问问。想理解一下这个，有什么用例吗？

**Comment by hchunhui** [comment]
暂无用例。从代码上看，大部分情况下 engine.acive_engine 就是 engine 自身，只有在打开方案选单（switcher）的时候，active_engine 会变成另一个引擎。

**Comment by Ace-Who** [comment]
谢谢。
