### ISSUE TITLE
如何获取原始输入码？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#29]
我是用来做字符串操作，修改 `cand.preedit`。直接读 `cand.preedit` 应该是出错了，因为不生成候选。目前我用的是 `context:get_script_text()`，这个应该是变换后的输入码吧？不过我的方案看不出来，因为本身没有做变换。

**Comment by hchunhui** [comment]
原始输入码怎么得到我不太清楚，不过我试了一下 `cand.preedit` 确实是可用的，只不过应该是变换后的输入码：
```lua
function show_preedit_filter(input)
   for cand in input:iter() do
      cand:get_genuine().comment = cand.comment .. " " .. cand.preedit
      yield(cand)
   end
end
```

**Comment by lotem** [comment]
`Candidate`本身不包含對應的輸入碼。可按照其起止位置取輸入碼對應區間的子串。

**Comment by Ace-Who** [comment]
但是首先需要获取全部输入码，没有 `get_raw_input` 这样的东西吗？

**Comment by Ace-Who** [comment]
@hchunhui 我重新测试了，应该没问题，就是变换后的输入码，之前出错可能是因为字符串处理中没考虑到这个变换。不过我这个问题主要是想获得完整的输入码，而不是候选对应的串。我设想是会有 `context:get_raw_input()` 这样的方法。

**Comment by Ace-Who** [comment]
发现有 `context.input` 直接可用，之前搜了几遍怎么没看到呢，问题应该是解决了。谢谢。
