### ISSUE TITLE
建议修改data示例以符合国标GB/T  9704-2012

### ISSUE THREAD

**Issue by CNMan** [hchunhui/librime-lua#30]
```
7.3.5.4  成文日期中的数字
用阿拉伯数字将年、月、日标全，年份应标全称，月、日不编虚位（即1不编为01）。

另外，党、政的公文日期格式是不同的，党口的公文是小写阿拉伯如2020年2月14日，政口的是大写二〇二〇这样的
```

即需要1、小写不编虚位；2、增加大写

另外：

1. 请将 #4 中`week`也加入示例吧
2. reverse.lua没有处理轻声即5显示

![reverse lua](https://user-images.githubusercontent.com/8692234/74626125-b1962d00-5189-11ea-8d87-7a109a60c5a2.png)

**Comment by hchunhui** [comment]
1. 不打算修改示例中的日期格式。示例主要目的是演示脚本的写法，如 `date.lua` 主要想演示 translator 怎么写，候选项怎么生成。日期格式是次要的，故用了 lua 默认的编虚位的格式。有特殊需要的人不难从这个脚本开始写出自己的版本。
2. 题主可以考虑另开代码库，收集各种有用的脚本，如国标日期、大写、星期等，方便大家选用。
3. `reverse.lua` 没有轻声是 bug，是我抄地球拼音的转写规则抄漏了一行，待会改。
