### ISSUE TITLE
求救，请问为什么这个简单的 lua_filter 会让内存不降下来？

### ISSUE THREAD

**Issue by iDvel** [hchunhui/librime-lua#307]
```lua
function test_filter(input)
    local l = {}

    local i = 0
    for cand in input:iter() do
        if i % 2 == 0 then
            yield(cand)
        else
            table.insert(l, cand)
        end
        if #l > 100 then
            break
        end
    end

    for _, cand in ipairs(l) do
        yield(cand)
    end
    for cand in input:iter() do
        yield(cand)
    end
end
```

我挂了两个类似逻辑的 lua_filter 给候选项做排序用，
https://github.com/iDvel/rime-ice/blob/main/lua/long_word_filter.lua
https://github.com/iDvel/rime-ice/blob/main/lua/pin_cand_filter.lua
每次看内存都是 100M~300M 左右。

如果不用这两个 Lua，内存会始终稳定在一个小区间；一直使用，内存就会慢慢增加，不会自动下降。

https://github.com/hchunhui/librime-lua/assets/14658234/1b909ddb-9161-40fc-ba04-53150349b58b

手动多次执行 `collectgarbage()` 后会降下来。
```lua
function test_translator(input, seg)
    local cand = Candidate("", seg.start, seg._end, ("%.f"):format(collectgarbage('count')), "")
    cand.quality = 100
    yield(cand)
    if input == "xxx" then
        collectgarbage()
        local cand = Candidate("", seg.start, seg._end, "collectgarbage()", "")
        cand.quality = 100
        yield(cand)
    end
end
```

https://github.com/hchunhui/librime-lua/assets/14658234/c705b26c-2f4b-4dbd-bb39-4e103622de6e

**Comment by shewer** [comment]
用 segment.prompt 顯示  mem
```lua
--
-- info.lua
-- patch:
--   engine/filters/@next: lua_filter@*info
--
local F={}
function F.init(env)
end
function F.fini(env)
end

function F.tags_match(seg,env)
  seg.prompt=seg.prompt .. (" luaMEM : %.f"):format(collectgarbage('count'))
  return false
end

function F.func(inp,env,clist)
end
return F
```

**Comment by shewer** [comment]
好多了   ， 不管怎麼 輸入 都在  8.9M

ttotetutobtnetotttttoetteutttoeutoteutoteutoeutoeuoeu=>井溫水泄入荓灩人茅山苁叢山多久灔井人廿水勒克萊爾前漢井井廿氽
  廿假山廿井假山苁叢山苁叢山廿假山廿假山假山]
schema: cangjie5 / 倉頡五代
status: composing
I20240203 17:26:31.828428 3725728 menu.cc:27] preparing 9 candidates.
I20240203 17:26:31.828505 3725728 dictionary.cc:119] creating temporary dict entry '汬'.
I20240203 17:26:31.828956 3725728 translation.cc:112] translation #0 has been exhausted.
I20240203 17:26:31.829049 3725728 config_component.cc:103] read: menu/alternative_select_labels
I20240203 17:26:31.829078 3725728 config_data.cc:222] traverse: menu/alternative_select_labels
[tt ete eto ttt eutt o thu toteu nnno ettu tt o t e tutob tneto tttt t oe t teut ttoeu toteu toteu t oeu t oeu oeu]| : **8917**

**Comment by shewer** [comment]
單純環境  872K
[ba ba ba b ba ba ba ba ba b t k te te]| : 872
page: 1  (of size 5)
1. [爸爸爸爸爸爸爸爸巴別塔卡特特]
2.  爸爸
3.  巴巴
4.  粑粑
5.  八八
