### ISSUE TITLE
使用 librime 1.9.0  ( without class path )  编译错误

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#319]
如题

**Comment by mokapsing** [comment]
不匹配肯定会报错吧，自己回退一下对应的commit应该就可以了

**Comment by shewer** [comment]
HEAD  on d402755

![image](https://github.com/hchunhui/librime-lua/assets/8329922/

b8eba98c-9aa5-45a2-b810-2e1874a58259)

**Comment by mokapsing** [comment]
如果试用 librime 1.9.0 配合最新的librime-lua  那么把https://github.com/hchunhui/librime-lua/commit/cf2c5722b9d9f2f05e1ead1b9959d9a7f84f06c2 去掉就可以了

**Comment by shewer** [comment]
那麼compat 不就失去作用了

**Comment by hchunhui** [comment]
应该fix了，多谢指出。原来写compat的时候没有认真测。
