### ISSUE TITLE
請教：怎麼實現在輸入数字后輸入的句號是小數點

### ISSUE THREAD

**Issue by Newdea** [hchunhui/librime-lua#328]
輸入數字是直接就上屏了，感觉沒法用lua處理，但要實現这功能，只能通过lua，一時想不到思路。

**Comment by mokapsing** [comment]
rime不是默认这样吗

**Comment by Newdea** [comment]
我的方案没有起效，但切换默认的方案试了下，是可以正常使用的。
我再找下原因吧，多谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 下午4:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hchunhui/librime-lua] 請教：怎麼實現在輸入数字后輸入的句號是小數點 (Issue #328)




 
rime不是默认这样吗
