### ISSUE TITLE
sync throws `Error opening db '...': IO error: lock .../...userdb/LOCK: already held by process` when both `Memory` and `table_translator@...` use the same dict

### ISSUE THREAD

**Issue by sci-42ver** [hchunhui/librime-lua#330]
Based on `rime-fast-xhup` and [this issue](https://github.com/hchunhui/librime-lua/issues/301#issuecomment-1899601521), I use the following to write one custom word to the userdb.
```lua
dict_ns = 'melt_eng'
-- in init
env.mem = Memory(env.engine, Schema('double_pinyin_flypy'), dict_ns)
...
-- in func
dict.text = inp
dict.custom_code = inp.." "
dict.comment = '(to add)'
local ph = Phrase(env.mem, "en_custom", seg.start, seg._end, dict)
yield(ph:toCandidate())
```

Although it has the advantage of loading the committed word automatically without re-deploy, but it will [throw `Error opening db '...': IO error: lock .../...userdb/LOCK: already held by process` error when sync in Fcitx5, etc., but not in weasel](https://github.com/fcitx/fcitx5-rime/issues/97#issue-2244182150) where the latter probably solves with this situation inherently. Then we can use `file` module to manually append the entry to the YAML or txt file, but that will need re-deploy.

Is there one way to avoid the above error but also keep the above advantage?

**Comment by mirtlecn** [comment]
我在 Weasel 不久之前也碰到过这个 error。在某个时间点后突然消失了。你提到了 issue：

https://github.com/rime/weasel/issues/199

我可以确定，这个问题在 15.0 的某个版本还是有的。

另外，补充，我遇到的问题是：**即使 Memory 对象没有调用对应的方案**，error log 里面也会提示被锁定，并且程序还会尝试重建用户词典。所以，这个问题我当时并不确定是 Memory 引发的。

但几个月某个改动「修复」（?）了。因为我的配置里面存在用到 Memory 的地方，有的还是不同的 lua 打开同一个方案。同步的时候没有报错。

另外提供一个可能的解决方案（未验证）：将在 translator 里面设置 db_class: tabledb。

**Comment by shewer** [comment]
lua 中的 LevelDb  不支援 db_pool ( 可以多個翻譯器 同時參考己開啓的 userdb)
MemoryReg  類似 翻譯器 ，可以同時 和其他翻譯器共用同一個userdb 
 

如果  usredb 先被  LevelDb 開啓  將造成 Translator 無法開啓 userdb
檢查 方案中  lua script 是否有使用 LevelDb  開啓 userdb(  LevelDb) 

如果一定編輯LevelDb 操作 翻譯器的userdb ，最好是在 rime.lua 
 or init()  or fini()  ，中操作 且完工時  使用 :close() 關閉  

```lua
local db = LevelDb('luna_pinyin') 
db:open()
....
db:close()
```

**Comment by mirtlecn** [comment]
你好 @shewer ，如果在具体的 lua 中，比如：

```lua
local F = {}

function F.init( env )
  local config = env.engine.schema.config
  env.name_space = env.name_space:gsub( '^*', '' )
  local schema = config:get_string( env.name_space .. '/en_schema' ) or 'en'
  F.en_dict = Memory( env.engine, Schema( schema ) )

  env.commit_notifier = env.engine.context.commit_notifier:connect(
                                  function( ctx )
                local cand = ctx:get_selected_candidate()
                local commit_text = ctx:get_commit_text()
                local commit_code = ctx.input

                if (cand and cand.text == commit_text) then
                    if (cand.type == 'sentence' or cand.type == 'raw') and
                        ((commit_text:find( '%a' ) and commit_text:find( '%d' )) or (commit_text:find( '^%a+$' ))) then
                        log.info( '- record: ' .. commit_text )
                        F.update_dict_entry( commit_text, commit_code )
                    end
                else
                    return
                end
            end
                               )
    end
end

function F.update_dict_entry( text, code )
    if #text == 0 then return end
    local e = DictEntry()
    e.text = text
    e.custom_code = code .. ' '
    F.en_dict:update_userdict( e, 1, '' )
end

function F.func( input, env )
   for cand in input:iter() do yield( cand ) end
end

function F.fina( env )
  env.commit_notifier:disconnect()
end

return F
```

因为脚本中并没有显性地新建 db 这个对象，所以想问这两步是加在哪里呢？

在新建 memory 之前？在 disconnect 之后？

**Comment by shewer** [comment]
> 你好 @shewer ，如果在具体的 lua 中，比如：
> 
> ```lua
> local F = {}
> 
> function F.init( env )
>   local config = env.engine.schema.config
>   env.name_space = env.name_space:gsub( '^*', '' )
>   local schema = config:get_string( env.name_space .. '/en_schema' ) or 'en'
>   F.en_dict = Memory( env.engine, Schema( schema ) )
> 
>   env.commit_notifier = env.engine.context.commit_notifier:connect(
>                                   function( ctx )
>                 local cand = ctx:get_selected_candidate()
>                 local commit_text = ctx:get_commit_text()
>                 local commit_code = ctx.input
> 
>                 if (cand and cand.text == commit_text) then
>                     if (cand.type == 'sentence' or cand.type == 'raw') and
>                         ((commit_text:find( '%a' ) and commit_text:find( '%d' )) or (commit_text:find( '^%a+$' ))) then
>                         log.info( '- record: ' .. commit_text )
>                         F.update_dict_entry( commit_text, commit_code )
>                     end
>                 else
>                     return
>                 end
>             end
>                                )
>     end
> end
> 
> function F.update_dict_entry( text, code )
>     if #text == 0 then return end
>     local e = DictEntry()
>     e.text = text
>     e.custom_code = code .. ' '
>     F.en_dict:update_userdict( e, 1, '' )
> end
> 
> function F.func( input, env )
>    for cand in input:iter() do yield( cand ) end
> end
> 
> function F.fina( env )
>   env.commit_notifier:disconnect()
> end
> 
> return F
> ```
> 
> 因为脚本中并没有显性地新建 db 这个对象，所以想问这两步是加在哪里呢？
> 
> 在新建 memory 之前？在 disconnect 之后？

F.fina  錯了    是 F.fini(env)   notifier 無法解構容易出問題

**Comment by mirtlecn** [comment]
感谢指正，不过这个是 typo，复制，脱敏，到这里来的时候不小心打错了。

我本想问本 issue 提到的问题，因为 issue 提到的 error log 我曾经碰到过，但现在没有碰到过了。而本 issue 提到说其他平台仍然会有这个错误。

所以想问你提到的代码，是否能解决这个问题，如果能的话，应该加在脚本的哪里，是新建 Memory 对象前还是后，在 disconnect 前还是后？

```lua
local db = LevelDb('luna_pinyin') 
db:open()
....
db:close()
```

**Comment by shewer** [comment]
如果沒用  LevelDb  就不用在意

**Comment by mirtlecn** [comment]
> Mmory 內己註冊 commit_notifier 用不了嗎？
每次 commit 時就會 callback Memorize() , 參考 memory 範例腳本

这个脚本我记得是为了将 echo_translator 和特定编码的 sentence 候选写入用户词典的，本身候选不属于任何方案内，所以要手动写入。是正常工作且没有 error log 的。

但有一段时间每次同步，发现过本 issue 提到的

```log
IO error: lock .../...userdb/LOCK: already held by process
```

当时并没有找到问题所在，因为 erro log 中出现了没有在 lua 中调用的方案名，比如 Memory 所用的方案是 en，但 error log 提示 stroke db 无法打开的错误。

过一段时间，突然好了。

现在看到这个 issue，又想起来了。

**Comment by sci-42ver** [comment]
> 如果沒用 LevelDb 就不用在意

 感谢热情的 shewer 回复，您 issue 里的回复对我的帮助很大。

参考我的 1st comment，并没有使用 LevelDb。

如果是这样的话，我抽空用您的 LevelDb 试一下。`db:close` 应该放在 `func` 里对吧，放在 `fini` 里面，印象中只会在切换 schema 时调用。

**Comment by sci-42ver** [comment]
> 我可以确定，这个问题在 15.0 的某个版本还是有的。

那我不太清楚了，我的 `weasel` 0.15.0 没有这个问题，`weasel` 代码我没怎么看过，具体为啥会(帮助/不)解锁 LOCK 不太清楚。

> 另外，补充，我遇到的问题是：**即使 Memory 对象没有调用对应的方案**，error log 里面也会提示被锁定，并且程序还会尝试重建用户词典。所以，这个问题我当时并不确定是 Memory 引发的。

我这里试过了，把 Memory 关掉后，其他全部不动，不会出现上述报错，可以正常 sync 了 (否则 LOCK 相关用户词典无法 sync)。您的情况我不是太清楚，可能和我的有点区别。

> 另外提供一个可能的解决方案（未验证）：将在 translator 里面设置 db_class: tabledb。

嗯，目前我是这样处理的（见 imfuxiao/Hamster#593）

**Comment by shewer** [comment]
LevelDb 主要是提供  librime-lua 大量的 key value  db  應用
雖然可以開啓 userdb   但是要小心 操作

**Comment by sci-42ver** [comment]
使用 `Schema(env.name_space)` 配合 `lua_translator@en_custom_translator` 确实不会 LOCK，因为使用的词典是只属于此 lua 脚本的。此时 `env.name_space=en_custom_translator`。

上述方案可以通过 `yield(ph:toCandidate())` 产生 candidate。但是 `env.mem:memorize(memoryCallback1)` 并不运行 `memoryCallback1` (在此函数最开始加了 `log.info`，但是 log 里并不产生此 info)。最后效果是可以同步，但是并不能自造词 `...*`。

---

有一个现象比较奇怪: 第一次输入 `foobar*`，如果使用 `ph.quility = 100`，其会列为第一候选，但是第二次输入的时候，其会被列为第二候选。使用 `log.info` 在 `if inp:match("%*$") then` block 最开始，两次应该都是运行的 `yield(ph:toCandidate())`。

**Comment by mokapsing** [comment]
> 但是，此时 `env.name_space=en_custom_translator`，应该需要一个对应的 `en_custom_translator.schema.yaml`。

这个结论怎么来的

**Comment by mirtlecn** [comment]
刚刚试了下 leveldb，改了下 repo 的 sample，可以作为用户词典用

```lua
-- ecdict:
--  dictionary: lua
--  initial_quality: 1.5 

db_pool_ = {}

local function opendb( name )
    local db = db_pool_[name]
    if not db then
        db = LevelDb( name )
        if not db then return nil end
        db_pool_[name] = db
    end
    if not db:loaded() then db:open() end
    return db
end

local function update_entry( text, code, db )
    if #text == 0 then return end
    db:update( code, text )
end

local M = {}

function M.init( env )
    local config = env.engine.schema.config
    local dbname = config:get_string( env.name_space .. '/dictionary' )
    env.quality = tonumber( config:get_string( env.name_space .. '/initial_quality' ) ) or 1
    env.db = assert( opendb( dbname ), 'initleveldb failed' )

    env.commit_notifier = env.engine.context.commit_notifier:connect(
                              function( ctx )
            local commit_text = ctx:get_commit_text()
            local commit_code = ctx.input
            print( '- record: ' .. commit_text )
            update_entry( commit_text, commit_code, env.db )
        end
                           )
end

function M.fini( env )
    env.db:close()
    env.commit_notifier:disconnect()
end

function M.func( inp, seg, env )
    for _, v in env.db:query( inp ):iter() do
        local type = 'lua'
        local cand = Candidate( type, seg.start, seg._end, v, '+' )
        cand.quality = env.quality
        yield( cand )
    end
end

return M
```

不过我用 rime_dict_manager 没办法导出数据，不晓得怎么方便地备份里面的 key value

**Comment by shewer** [comment]
> 使用 `Schema(env.name_space)` 配合 `lua_translator@en_custom_translator` 确实不会 LOCK，因为使用的词典是_只属于此 lua 脚本_的。
> 
如果方案中有 該字典的 namespace  可以參考 下面 create mem
```lua
Memory( engine, schema[,ns])  
Memory(env.engine, env.engine.schema) -- 使用用本方案ns="translator"
Momory(env.engine, Schema('cangjie5') ) -- 使用外部方案 ns=translator
Memory(env.engine, Schema('cangjie5'), 'cangjie6') ns='cangjie6'
```


> 但是，此时 `env.name_space=en_custom_translator`，应该需要一个对应的 `en_custom_translator.schema.yaml`。然后，主 schema.yaml 添加 `table_translator@en_custom_translator` 来导入自造词。这样的话依然会有 "Error opening db 'en_custom_translator': IO error: lock .../en_custom_translator.userdb/LOCK: already held by process" message。"
> 
> 暂时可以切换方案来同步 (即_只使用一个 schema_ 来自造英文词汇)，因为 `lua_translator@en_custom_translator` 是[只属于一个 schema](https://github.com/hchunhui/librime-lua/issues/156#issuecomment-1030741659) 的。之前由于几个 schema 都用了 `lua_translator@en_custom_translator` （名字不一样，不过都调用同一个 lua 脚本。），故切换方案无效。
> 
> 请问有办法做 `db:close()` 类似的操作于 userdb，从而不切换方案也可同步？(在 hamster 上，切换方案并不会自动释放 LOCK。见 问题里引用的第2个链接 [fcitx/fcitx5-rime#97](https://github.com/fcitx/fcitx5-rime/issues/97))
> 
> 1. 上述方案可以通过 `yield(ph:toCandidate())` 产生 candidate。但是 `env.mem:memorize(memoryCallback1)` 并不运行 `memoryCallback1` (在此函数最开始加了 `log.info`，但是 log 里并不产生此 info)。

> 2. 不清楚上述 `commits:update_entry` 是不是一个 pseudo code，文档里用的是 `memory:update_userdict` （memory是一个 `Memory` instance）。

新版本 librime-lua 已在 CommitEntryReg 加入 update_entry methods , 所以不須要引用 upvalue
舊版本是使用 upvalue 機制取得 mem 
```lua
--old
env.mem:memorize( function(commits)  callback(env.mem,commits) end) -- callback(mem,commits)
--new
env.mem:memorize( callback1) -- callback1(commits)
```

剛剛 測試 ，在mem 中開啓的 userdb  , 無法再用 leveldb 操作
```
mem 生成後 userdb 始終開啓，LevelDb 也是無法開啓， 
mem.user_dict.loaded   -- true
leveldb._loaded -- false
leveldb:close() --  false   , close() 程序會先檢查 loaded 狀態再執行 ，所以 close 失敗 
leveldb:open()  -- error  無法開啓
```

我在 fini 中  加入 env.mem = nil   提前清除 期望提前 gc  , 你可試試，
rime_api_console 版本
ver : "    (id:unknown)  Ver: librime 1.11.0 librime-lua 287 lua Lua 5.4"

**Comment by mirtlecn** [comment]
请教一个问题，这个 leveldb 的数值可以像 librime 的 userdb 借助 librime cli 导出、合并吗？@shewer

似乎 rime_dict manager 导出的是只有文件头的空内容，

倒是发现用 

```lua
for k,v in env.db:query(''):iter() do
    print (k,v)
end
```

能获取一份内容。是不是只能在 lua 里面这些合并、导出的操作。

**Comment by sci-42ver** [comment]
> > 但是，此时 `env.name_space=en_custom_translator`，应该需要一个对应的 `en_custom_translator.schema.yaml`。
> 
> 这个结论怎么来的

@mokapsing 实际效果是这样 你可以自己试一下

**Comment by sci-42ver** [comment]
> 不过我用 rime_dict_manager 没办法导出数据，不晓得怎么方便地备份里面的 key value

@mirtlecn 这个意思是无法导出 userdb.txt 么？如果是这样，比较麻烦。

**Comment by sci-42ver** [comment]
> 我在 fini 中 加入 env.mem = nil 提前清除 期望提前 gc , 

@shewer 加了 log，确实会提前 `env.mem = nil`，然后，进行同步。但是 LOCK 并没有释放。

**Comment by shewer** [comment]
> > 我在 fini 中 加入 env.mem = nil 提前清除 期望提前 gc ,
> 
> @shewer 加了 log 进行查看，确实会提前 `env.mem = nil`，然后，进行同步。但是 LOCK 并没有释放。
> 
> 我 Fcitx5 用的是 [Arch Linux 编译好的 1.10.0](https://archlinux.org/packages/extra/x86_64/librime/)

查查   librime-lua 的版本
```lua
 local function find_ver()
    if Component and Component.TableTranslator then
       return 287
    elseif UserDb and TableDb then
       return 240
    elseif UserDb then
       return 220
    elseif rime_api.regex_match then
       return 197
    elseif rime_api.get_distribution_name then
       return 185
    elseif LevelDb then
       return 177
    elseif Opencc then
       return 147
    elseif KeySequence and KeySequence().repr then
       return 139
    elseif  ConfigMap and ConfigMap().keys then
       return 127
    elseif Projection then
       return 102
    elseif KeyEvent then
       return 100
    elseif Memory then
       return 80
    elseif rime_api.get_user_data_dir then
       return 9
    elseif log then
       return 9
    else
       return 0
    end
 end
```

**Comment by sci-42ver** [comment]
> 查查 librime-lua 的版本

https://gitlab.archlinux.org/archlinux/packaging/packages/librime/-/blob/main/PKGBUILD?ref_type=heads#L9 -> https://github.com/hchunhui/librime-lua/tree/7f3eca2ce659fc2401b8acb52bd2182b433e12b1

不太清楚您发的这个 `find_ver` 作用 (如果是要确保每个都有效 应该是要加 `not`吧)，运行结果为 287。

**Comment by mirtlecn** [comment]
玩了一会 leveldb，用做临时的词典的话，刚刚能用。

导入导出不成问题，但权重可能有点麻烦

https://github.com/mirtlecn/rime/blob/master/tools/lua/leveldb.lua

***

不清楚这个 issue 提到的问题如何解决

**Comment by sci-42ver** [comment]
> https://github.com/mirtlecn/rime/blob/master/tools/lua/leveldb.lua

试了一下，这样即使多个 schema 共用这个 db 也没有问题，因为 `db.close()` 同时 `sync` 完全分离出来了。

这样规避了 `table_translator`，从而不会有两个 translator 抢占一个 LOCK 的情况。

**Comment by sci-42ver** [comment]
@shewer  可以再问一个小问题么（不属于本 issue 问题）？

我想着用 rime 默认删词按键 ^K 来删除上述手动管理的 tabledb 某一个词汇，可以通过 lua_processor 删除 (返回2)，但是无法像 rime 删除词汇那样及时更新。我是用上一个 comment 方法来手动产生 candidate 的。

---

现象是通过 log 查看，后续的 lua_translator 和 lua_filter 都不调用 (在仅按下 ^K 情况下)。

librime 里应该是通过 https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime/context.cc#L263
刷新的，但是 lua_translator 和 lua_filter 好像并不接受 notifier, 除非输入 alphabet 里的字符。

**Comment by sci-42ver** [comment]
感谢。之前弄错了，由于 lua_translator 直接用 `Candidate` construct 候选项，`As<Phrase>` 会变成 `NULL`，所以之前 lua 里用 `delete_current_selection` 无效。

lua 里直接调用 `refresh_non_confirmed_composition` 来刷新 `kGuess`，可行。

**Comment by shewer** [comment]
發現 user_dict 是leveldb 時 
須要操作 StartSession() FinishSession() DiscardSession()
Memory::OnCommit() 時須要 call StartSession()
TableTranslation ScriptTranslation 在產生 Translation 前
會 call FiniSession()

**在 callback 外部操作 update_entry  會少了 StartSession() 操作**
  



Memory::OnCommit()
https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime/gear/memory.cc#L104

TableTranslaion     ScriptTranslation   開始時 call FinishSession()
https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime/gear/table_translator.cc#L249

https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime/gear/script_translator.cc#L198

class LevelDb
https://github.com/rime/librime/blob/1f3bf35691a5ad066ef36775e289525f3b092e28/src/rime/dict/level_db.h#L35

**Comment by mirtlecn** [comment]
这个 bug 打算如何处理呢？

是禁止在 memory callback 外使用 update_entry，抛出明确的错误或者警告，还是如何?
