### ISSUE TITLE
【Bug】Memory 对象会导致 Rime 无法同步

### ISSUE THREAD

**Issue by mirtlecn** [hchunhui/librime-lua#335]
如 #330 所示

Memory 无法用于已经启用，且用户词典打开（默认情况）的方案，会导致大部分前端同步时抛出词典锁定的错误。

而如果想要使用 Memory 对象，所用方案很可能为启用用户词典状态（默认），lua 并未阻止此危险操作。所以此设计似有问题。请确认。

## 复现

测试方案（内含报错信息）：

[test_lua.zip](https://github.com/hchunhui/librime-lua/files/15213109/test_lua.zip)

- 引入一个使用 Memory 对象的 lua，重新部署，该 Memory 对象指向 luna_pinyin
- 使用 luna_pinyin 打字，保证生成一些用户词
- 同步，各个前端报错，提示用户词典被其他程序锁定，部分前端用户词典无法同步。

有关问题的前端：ibus-rime，[Squirrel](https://github.com/iDvel/rime-ice/pull/643#issuecomment-1913577767) ，[fcitx5-rime](https://github.com/fcitx5-android/fcitx5-android/issues/410#issuecomment-2088863988)（不会显示错误，但无法继续同步）

## 预期情况

Memory 可以正常工作，不导致用户词典锁定。

或者以下情况均可：

- 在新建 Memory 时，若检索到用户词典为 leveldb，则提示用户无法进行操作，中止操作，保证前端正常同步；
- 另设一个函数，提供 Memory 所提供的检索固态词典的能力，不涉及用户词典
- 修复 Memory 函数，当且仅当使用了其关涉用户词典的操作时，才去尝试打开 leveldb

## 问题 lua

```lua
-- filter:
--   - lua_fiter@*test

local F = {}

function F.init( env )
    -- F.foo = Memory( env.engine, env.engine.schema) -- error
    -- local foo = Memory( env.engine, env.engine.schema)  -- no error
    -- env.foo = Memory( env.engine, env.engine.schema) -- error
end

function F.func( input, env )
    -- F.foo = Memory( env.engine, env.engine.schema) -- error
    local foo = Memory( env.engine, env.engine.schema) -- error
    -- env.foo = Memory( env.engine, env.engine.schema) -- error

    for cand in input:iter() do
        cand.comment = '*' -- make sure this lua being called
        yield( cand )
    end
end

return F
```

_Originally posted by @mirtlecn in https://github.com/hchunhui/librime-lua/issues/333#issuecomment-2094575070_

**Comment by mirtlecn** [comment]
此外：

样例里面的： 

https://github.com/hchunhui/librime-lua/blob/master/sample/lua/expand_translator.lua#L40

这个 lua，也会导致 rime 出错，无法同步。因为 Memory 对象用到了一个已经开启的方案，

同 #330

**Comment by shewer** [comment]
檢查 整個方案中有無 leveldb 實例，且已 loaded 
( 可以使用  :close() 關閉， 但可能再也開不起來了，因爲 user_dict 調用 db 是常開狀態 ）
   
如果有和 方案中是否有衝突
上次討論中有使用   lua  環境製造  db_pool_ 的腳本 ，要取消 
或是 用 :close()  全關閉. 

確保 lua 環境中  所有 leveldb 實例中 與 user_dict 衝突

還是一個原則  儘量不要用 leveldb 開啓 user_dict 的db

**Comment by mirtlecn** [comment]
> 檢查 整個方案中有無 leveldb 實例，且已 loaded ( 可以使用 :close() 關閉， 但可能再也開不起來了，因爲 user_dict 調用 db 是常開狀態 ）
> 
> 如果有和 方案中是否有衝突 上次討論中有使用 lua 環境製造 db_pool_ 的腳本 ，要取消 或是 用 :close() 全關閉.
> 
> 確保 lua 環境中 所有 leveldb 實例中 與 user_dict 衝突
> 
> 還是一個原則 儘量不要用 leveldb 開啓 user_dict 的db

你好。

该问题的测试环境是完全新的 ibus-rime 环境（Debian + ibus-rime + librime 1.85；Ubuntu + ibus-rime + librime 1.10），只加载了 issue 提到的一个 lua，这个 lua 只有一个功能，就是新建一个 Memory 对象。

```lua
-- test.lua
-- - lua_filter@*test
local F = {}

function F.init( env )
    print('init a memory')
    env.mem = Memory( env.engine, Schema( 'cn' ) ) -- any opened schema
    -- env.mem =  Memory( env.engine, env.engine.schema ) -- or currenbt schema
end

function F.func( input, env )
    for cand in input:iter() do
        cand.comment = '*' -- make sure this lua being applied
        yield( cand )
    end
end

return F
```

没有使用其他涉及 leveldb 的功能。

复现方法为：
- 引入 issue 提到的简单 lua，重新部署
- 用 Memory 用到的方案打一些字，保证生成了一些用户词
- 点击同步
- 出现错误，错误信息为「同步错误，xxx 方案被其他进程使用，锁定」

我不会 c++，但仅仅是猜测，是因为新建 Memory 的时候 lua 就会尝试访问 userd。进而导致同步错误。

**Comment by mirtlecn** [comment]
fcitx5-rime 似乎不会将错误写入 log，可能需要一些额外的操作。因此我选了 ibus-rime 测试

不知道你能否复现？

rime/home 有一个 issue 看 log 似乎也与此相关：

我觉得它是 bug 的原因是：
- 若这种 Memory 的使用方式有误，其造成的错误不应该在同步的时候才抛出，应当在新建 Memory 的时候就直接中止操作
- 检索固态词典，必须新建一个 Memory 对象，且无须访问 leveldb，当前的行为或许可以避免或优化

**Comment by shewer** [comment]
你可以先將  更新的 expent_translator.lua 重新下載
試試
commits  --> commit  變數名 錯誤
這個錯誤 只會造成 callback 呼叫 失敗  沒有無法開啓userdict 的問題

**Comment by mirtlecn** [comment]
我没有用那个 lua，整个方案只用了一个测试 lua，就是上面写的那个。

**Comment by mirtlecn** [comment]
[test_lua.zip](https://github.com/hchunhui/librime-lua/files/15213098/test_lua.zip)

@shewer

**Comment by mirtlecn** [comment]
如若诸位维护者有空，请确认此 issue 是否存在，或者给予指导。

个人已经在两台虚拟机的 fcitx5-rime 和 ibus-rime 稳定复现，且鼠须管、fcitx5 android 也有相关报错。rime/home 的一则 issue 据我判断也可能与此有关。

简易的测试方案和 lau 已经在主贴中提供。

@hchunhui @TsinamLeung （为当初引入该对象的贡献者）

感激不尽。

原因是此问题会影响多个前端，导致前端无法继续同步，且报错不指向 lua 错误而是指向用户词典被锁定。

**Comment by TsinamLeung** [comment]
> 如若诸位维护者有空，请确认此 issue 是否存在，或者给予指导。
> 
> 个人已经在两台虚拟机的 fcitx5-rime 和 ibus-rime 稳定复现，且鼠须管、fcitx5 android 也有相关报错。rime/home 的一则 issue 据我判断也可能与此有关。
> 
> 简易的测试方案和 lau 已经在主贴中提供。
> 
> @hchunhui @TsinamLeung （为当初引入该对象的贡献者）
> 
> 感激不尽。
> 
> 原因是此问题会影响多个前端，导致前端无法继续同步，且报错不指向 lua 错误而是指向用户词典被锁定。

我目前工作電腦還沒有測試還境，因此我見到你的Code我猜想是： 如果Memory沒有被回收則會佔用leveldb。
透過觀察前端的implementation,可以見到是rime_api的sync_user_data作全部同步操作的

```C++
RIME_API Bool RimeSyncUserData() {
  RimeCleanupAllSessions();
  Deployer& deployer(Service::instance().deployer());
  deployer.ScheduleTask("installation_update");
  deployer.ScheduleTask("backup_config_files");
  deployer.ScheduleTask("user_dict_sync");
  return Bool(deployer.StartMaintenance());
}

RIME_API void RimeCleanupAllSessions() {
  Service::instance().CleanupAllSessions();
}
void Service::CleanupAllSessions() {
  sessions_.clear();
}
// SessionMap session_
//  using SessionMap = map<SessionId, an<Session>>;
```
此步似乎是notify to release session.(這個操作應把Memory全部清空）
我認為短期解決方案是：
在每次F.func 中新建Memory實例，確保在function結束後能被Release（可能會導致效能下降）

之後可能需要lua component能夠捕獲到session deconstructing時的訊息，並傳遞給各Lua部件，調起sessionDestory的handler（需要用戶自行編寫）
這樣做的目的是因為，luaComponent是隨着librime加載而initialize的，僅當librime 關閉時，lua 的 context才會清空。因此需要自行管理自librime取得的組件

**Comment by mirtlecn** [comment]
> 在每次F.func 中新建Memory實例，確保在function結束後能被Release

感谢指导，我会测试并给予反馈

**Comment by mirtlecn** [comment]
> 在關閉 section 時  lua component 也會解構   LuaObj env_ 也會移除
> 可以試試 在  LuaMemory  LuaTranslator ....  有 Lua member 
> 解構時 加上lua_->gc();
> 
> 所有  關於 librime  物件  都要掛在 env 中 ，不能掛到 upvalue or global
> ```lua
> --module file
> local F={}
> local m_mem
> g_mem=nil
> function F.init(env)
>    env.mem = Memory(.....)
>     F.mem = env.mem  -- NG
>     m_mem = env.mem  -- NG
>     g_mem = env.mem -- NG
> end
> function F.func(inp, env)
>    local mem = env.mem   -- ok
> end
> ```

```lua
-- filter:
--   - lua_fiter@*test

local F = {}

function F.init( env )
    -- F.foo = Memory( env.engine, env.engine.schema) -- error
    -- local foo = Memory( env.engine, env.engine.schema)  -- no error
    -- env.foo = Memory( env.engine, env.engine.schema) -- error
end

function F.func( input, env )
    -- F.foo = Memory( env.engine, env.engine.schema) -- error
    local foo = Memory( env.engine, env.engine.schema) -- error
    -- env.foo = Memory( env.engine, env.engine.schema) -- error

    for cand in input:iter() do
        cand.comment = '*' -- make sure this lua being called
        yield( cand )
    end
end

return F
```

**Comment by shewer** [comment]
加上個 試試，在同步時 蜀發 engine 解構 lua_component 完成 fini 後 gc()
Memory       Component.Translator Processor .....
要掛在 env  
git apply   patch

```patch
diff --git a/src/lua_gears.cc b/src/lua_gears.cc
index 9e1f704..eaec381 100644
--- a/src/lua_gears.cc
+++ b/src/lua_gears.cc
@@ -159,6 +159,7 @@ LuaFilter::~LuaFilter() {
       LOG(ERROR) << "LuaFilter::~LuaFilter of "<< name_space_ << " error(" << e.status << "): " << e.e;
     }
   }
+  lua_-gc();
 }

 //--- LuaTranslator
@@ -186,6 +187,7 @@ LuaTranslator::~LuaTranslator() {
       LOG(ERROR) << "LuaTranslator::~LuaTranslator of "<< name_space_ << " error(" << e.status << "): " << e.e;
     }
   }
+  lua_-gc();
 }

 //--- LuaSegmentor
@@ -213,6 +215,7 @@ LuaSegmentor::~LuaSegmentor() {
       LOG(ERROR) << "LuaSegmentor::~LuaSegmentor of "<< name_space_ << " error(" << e.status << "): " << e.e;
     }
   }
+  lua_-gc();
 }

 //--- LuaProcessor
@@ -244,6 +247,7 @@ LuaProcessor::~LuaProcessor() {
       LOG(ERROR) << "LuaProcessor::~LuaProcessor of "<< name_space_ << " error(" << e.status << "): " << e.e;
     }
   }
+  lua_-gc();
 }

 }  // namespace rime
```

**Comment by shewer** [comment]
> > 在關閉 section 時  lua component 也會解構   LuaObj env_ 也會移除
> > 可以試試 在  LuaMemory  LuaTranslator ....  有 Lua member
> > 解構時 加上lua_->gc();
> > 所有  關於 librime  物件  都要掛在 env 中 ，不能掛到 upvalue or global
> > ```lua
> > --module file
> > local F={}
> > local m_mem
> > g_mem=nil
> > function F.init(env)
> >    env.mem = Memory(.....)
> >     F.mem = env.mem  -- NG
> >     m_mem = env.mem  -- NG
> >     g_mem = env.mem -- NG
> > end
> > function F.func(inp, env)
> >    local mem = env.mem   -- ok
> > end
> > ```
> 
> ```lua
> -- filter:
> --   - lua_fiter@*test
> 
> local F = {}
> 
> function F.init( env )
>     -- local foo = Memory( env.engine, env.engine.schema)  -- no error
>     -- env.foo = Memory( env.engine, env.engine.schema) -- error
> end
> 
> function F.func( input, env )
>     local foo = Memory( env.engine, env.engine.schema) -- error
>     -- env.foo = Memory( env.engine, env.engine.schema) -- error
> 
>     for cand in input:iter() do
>         cand.comment = '*' -- make sure this lua being called
>         yield( cand )
>     end
> end
> 
> return F
> ```
Memory 中有 OnCommit(ctx)   掛在  translation 中 怪怪的

```
F.fini(env)
   env.mem=nil
   collectgarbage('collect')
end
```

**Comment by mirtlecn** [comment]
不好意思，改源码然后编译测试，我暂时没这个条件，虚拟机里面编译 boost 和 librime 很慢，会卡死。

**Comment by shewer** [comment]
lifetime   env 底下的 一定大於  func 下的 local var


在 func 中    local mem 參考 env.mem   執行完 回收 mem  
func(inp,env)
   local mem = env.mem 
end  --  distory  mem [point to  env.mem]

**Comment by mirtlecn** [comment]
> lifetime env 底下的 一定大於 func 下的 local var
> 
> 在 func 中 local mem 參考 env.mem 執行完 回收 mem func(inp,env) local mem = env.mem end -- distory mem [point to env.mem]

赋值 nil 并 collectgarbage('collect') **不会**导致同步错误！

当前测试了 ibus-rime 是成功解决了问题。其他的还没测试，

@shewer 

```lua
local F = {}

function F.init( env )
    env.mem = Memory( env.engine, env.engine.schema)
end

function F.func( input, env )
    for cand in input:iter() do
        cand.comment = '-' -- test if this lua has been called
        yield( cand )
    end
end

function F.fini(env)
   env.mem=nil
   collectgarbage('collect')
end

return F
```

**Comment by shewer** [comment]
影響不大  ， 只發生在 session close ()
還有更頻繁的   LuaTranslation

**Comment by mirtlecn** [comment]
谢谢你的帮忙。

你可以在 PR #338 的描述中，加入 
```txt
close #335
```

的字样，让该 PR 合并时，自动关闭此 issue。

**Comment by hchunhui** [comment]
依赖gc释放内存以外的资源并不是很合理，因为gc的时机本来就是不确定的。最好是能给 `Memory` 加一个 `close()` 或 `release()` 之类的方法，在 `fini()` 里面手动确保释放掉它打开的词典。

**Comment by shewer** [comment]
根據上述狀況   ComponentReg 可能也有問題  ， table_translator script_translator 也是屬於 Memory 類

Memory   成員有 字典(unique_ptr) 和 notifier  要如何解構 自己？
env.mem:close()   ？

原來的想法是 env （LuaObj) 在消滅時  env 下面的 userdata 
就可以被回收了，所以在此時觸發一次 gc()

**Comment by TsinamLeung** [comment]
But never rely on GC if so it must be our mechanism

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
