### ISSUE TITLE
没有可靠的方法区分 history 候选和其他候选

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#34]
`history` 翻译器的候选好像没有什么特征，在和其他候选混在一起的时候，无法完全可靠地区分两者。顺便提一下，虽然和 lua 无关，`history` 的配置项也很少，比如没有 `comment_format`，还有退格和回车会清空历史这样的限制，各种不便。更一般性地，rime 没有让翻译器给候选打标记的机制，有些需求解决起来就比较绕。

**Comment by hchunhui** [comment]
所以我比较关心在有了 notifier 之后，`history_translator` 能不能在 lua 这边实现出来？如果不能，还要绑定哪些东西？

如果能，针对区分问题，可以在 `yield` 历史候选时指定一个新的类型，这样就能用 `cand.type` 来区分。其他的如清空的时机也可以按自己的理解去做。

**Comment by Ace-Who** [comment]
lua 的实现不是挺简单吗？我还以为你已经做过了。我没有重点使用 lua 版的 `history_translator`，因为这个基础的功能还是希望不依赖插件，而是在此基础上做了根据历史联想候选的 `translatror`。
