### ISSUE TITLE
升级mac鼠须管18之后log.info无效

### ISSUE THREAD

**Issue by Urie96** [hchunhui/librime-lua#340]
不仅如此，下面这个require在16.2上可以，但升级到18之后也会导致lua整个插件失效
```lua
package.cpath = os.getenv("HOME") .. "/Library/Rime/lua/lib/lib?.so;" .. package.cpath
local timer = require("timer")
```

**Comment by shewer** [comment]
> 不仅如此，下面这个require在16.2上可以，但升级到18之后也会导致lua整个插件失效
> 
> ```lua
> package.cpath = os.getenv("HOME") .. "/Library/Rime/lua/lib/lib?.so;" .. package.cpath
> local timer = require("timer")
> ```

#313
