### ISSUE TITLE
如何通过rime.lua实现用输入法调用外部程序，类似多多输入法的直通车功能？

### ISSUE THREAD

**Issue by dbv771** [hchunhui/librime-lua#35]
很喜欢多多输入法的直通车功能，可以通过按键触发调用制定的程序。多多输入法是通过run函数实现的，在lua里面我尝试通过translator引擎在函数定义里面调用os.execute也可以实现，但存在一个问题，在translator里面输入的按键候选框会一直显示，不会自我关闭。我想应该在proceesors引擎里实现，但具体该如何写我试了几次都没成功。具体方法如下，在
if (input == "time" or input == "iuju" or input == "sj" or input == "dqsj") then
......
end
代码段下面添加如下代码
   if (input == "otc") then
   os.execute("C:\\TotalCommander922\\TOTALCMD.EXE")
   end

**Comment by hchunhui** [comment]
在proceesors引擎里实现这个思路应该是可以的。原来代码的几个问题：
- 调用外部程序用 `io.popen` 更好，因为 `os.execute` 会等待程序结束，可能造成输入法卡死
- 反斜杠在双引号里面要转义，即 `"\\"` 而不是 `"\"`
- 可以用 `context:clear()` 清空输入框

参考如下代码：
```lua
function executor(key, env)
   local engine = env.engine
   local context = engine.context
   local kNoop = 2
   if context.input == "otc" then
      io.popen("C:\\TotalCommander922\\TOTALCMD.EXE")
      context:clear()
   end
   return kNoop
end
```
在配方中 `processors` 下加入 `lua_processor@executor` 即可。

**Comment by dbv771** [comment]
经过在我的两台电脑上尝试以上方法，都没成功，不知道哪里出问题了，不过发现在translator的方案如果加上模拟按键esc似乎就可以解决候选框的问题，正在施工尝试中

**Comment by hchunhui** [comment]
我又试了一次，发现是 `processor` 的顺序问题，可试着将 `lua_processor@executor` 放到列表首位。

**Comment by dbv771** [comment]
不知道为什么还是不行，可以将你的rime.lua发出来我试一下吗

**Comment by hchunhui** [comment]
我的 rime.lua 已经改为与前面给的代码一样（除了要运行的程序外）。`lua_processor@executor` 放到 `processors` 首位可以成功，放到末位则不行。是不是要执行的程序路径填错了？

**Comment by lqqgis** [comment]
> 
> 
> 我的 rime.lua 已经改为与前面给的代码一样（除了要运行的程序外）。`lua_processor@executor` 放到 `processors` 首位可以成功，放到末位则不行。是不是要执行的程序路径填错了？

我按照上面的，将`lua_processor@executor`放到`processors`首位，出现了打开的应用闪退的情况，就是应用窗口弹出后马上关闭了

**Comment by redleafnew** [comment]
> 在proceesors引擎里实现这个思路应该是可以的。原来代码的几个问题：
> 
> * 调用外部程序用 `io.popen` 更好，因为 `os.execute` 会等待程序结束，可能造成输入法卡死
> * 反斜杠在双引号里面要转义，即 `"\\"` 而不是 `"\"`
> * 可以用 `context:clear()` 清空输入框
> 
> 参考如下代码：
> 
> ```lua
> function executor(key, env)
>    local engine = env.engine
>    local context = engine.context
>    local kNoop = 2
>    if context.input == "otc" then
>       io.popen("C:\\TotalCommander922\\TOTALCMD.EXE")
>       context:clear()
>    end
>    return kNoop
> end
> ```
> 
> 在配方中 `processors` 下加入 `lua_processor@executor` 即可。

老大，如果目录中有空格，如果表示？

**Comment by shewer** [comment]
"\\ "  我猜

**Comment by redleafnew** [comment]
两个`"`外面又加了`'`可以了
如`'"C:\\Program Files\\Rime\\weasel-0.15.1\\"'`

**Comment by wakin20** [comment]
照上面方法试过后还是会卡死系统，不知是不是更新了rime.dll所致。现在用的rime.dll版本为1.16.1.0。

**Comment by shewer** [comment]
先用  lua  REPL 試試看
