### ISSUE TITLE
dictiter_lookup 方法不支持检索词组

### ISSUE THREAD

**Issue by boomker** [hchunhui/librime-lua#369]
如下代码：
```lua
        local word_yin_code = input:sub(1, 4)
        local wd = env.mem:dictiter_lookup(word_yin_code, true, 50) -- expand_search
        for entry in wd:iter() do
            local et = entry.text
            logger.writeLog("xx: " .. et)
        end
```
发现日志里没有打印出词典里的词组，可以打印出单字，这是为什么呢，是姿势不对，还是说本来就不支持
@shewer ，大佬有空帮忙指点一下，多谢🙏

**Comment by shewer** [comment]
看不出有什麼問題，會不會是 word_yin_code    的字根  沒有詞組 或是 權重排不上   50個之內

Dictionary::LookupWords ()  會經過 prism 轉換再查 table 字典
如果 prism 轉換出多套字根 再去查table 說不定 50個不夠

**Comment by boomker** [comment]
我用的是双拼，两个编码字符为音码，比如 输入 `uiui` 会出现二字词组，我现在想按下 `/xy`后， 过滤词组中形码包含`xy` 条目

**Comment by boomker** [comment]
更新：
后来换了个方法解决了
```
    env.script_translator = Component.Translator(env.engine, schema, "", "script_translator@translator")
    local word_cands = env.script_translator:query(input, seg)
    ...
```

**Comment by boomker** [comment]
换了一个方法实现后，发现同步用户词库 的时候，有报错：
![image](https://github.com/user-attachments/assets/96c49705-dd91-41c3-9172-c9129f8d69ee)

我参照的代码是这里：
https://github.com/hchunhui/librime-lua/blob/b210d0cfbd2a3cc6edd4709dd0a92c479bfca10b/sample/lua/component_test.lua#L138

@shewer 大佬，帮忙指点下，谢谢🙏

**Comment by shewer** [comment]
env.tran  一樣是發生   userdict 沒有關閉，


試試   Component.ScriptTranslator( .... )   參數一樣

和 Memory  一樣  要disconnect()
```
 function init(env)
     env.tran= ...
 end
function fini(env)
     env.tran:disconnect()
end
```

或是 
```
function fini(env)
   env.tran = nil  
   collectgarbage(...)
end
```
   
end

**Comment by boomker** [comment]
最终通过这个方法解决了问题:

> 試試 Component.ScriptTranslator( .... ) 參數一樣

感谢大佬👍
