### ISSUE TITLE
preedit 只能依托于候选吗？

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#37]
要修改的话，只能通过 `cand.preedit`，在没有候选时，有办法修改吗？

**Comment by hchunhui** [comment]
不清楚。

**Comment by Ace-Who** [comment]
谢谢。

**Comment by lotem** [comment]
如果所求必須是`preedit`，那一般得有候選。
沒有的時候`preedit`會取那部分未經轉換的輸入串。
有的地方用了一個輸入長度爲零的候選，比如〔方案選單〕。

**Comment by Ace-Who** [comment]
好的，谢谢。
