### ISSUE TITLE
如何构造一个CommitRecord并将其推入commit_history

### ISSUE THREAD

**Issue by boomker** [hchunhui/librime-lua#374]
我有以下代码：
```lua
    local commit_history = context.commit_history
	commit_history:push(CommitRecord(cand.type, cand_txt))
```
但是好像不生效，大佬帮忙看看，谢谢🙏

**Comment by shewer** [comment]
沒有 CommitRecord()   這個function 
push  兩個參數 ( stirng, string)  -- cand.type, cand.text :  直接替代 CommitRecord(type, text)
                           (composition, string)  -- context.composition,  context.text , 可以參考  librime   CommitRecord::Push()
