### ISSUE TITLE
获取方案中任意节点的配置

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#38]
主要是想确认是否无法获取 `map` 和 `list` 的数据，因为 `config` 没有 `get_map()` 或 `get_list()` 这样的方法。

**Comment by hchunhui** [comment]
可以获得 map 和 list 里面的数据，我记得 `get_int()` 等的输入可以是带 `/` 的路径，与 librime 补丁的语法应该一样。但是没有办法得到 map 和 list 本身，这导致没有办法对 map 的键名作遍历。

**Comment by Ace-Who** [comment]
对，就是想获得整个节点的数据。可惜。
