### ISSUE TITLE
上屏输入码中一个段落的候选

### ISSUE THREAD

**Issue by Ace-Who** [hchunhui/librime-lua#39]
例如输入了 `abc`，要上屏或获取 `ab` 对应的任意候选。不知道这和 `context` 的 `pop_input()` `reopen_previous_segment()` 等方法有没有关系？尝试通过修改 `caret_pos` 来改变光标位置，没有起作用。

**Comment by hchunhui** [comment]
不清楚，librime 也没有文档说明。建议去搜一下 librime 中出现这些调用的代码，然后看它们的作用。

**Comment by Ace-Who** [comment]
谢谢，那就慢慢研究了。
