### ISSUE TITLE
请问Windows要如何安装这个插件？

### ISSUE THREAD

**Issue by Youxikong** [hchunhui/librime-lua#41]
从releases下载了插件，无论是readme.md还是下载的压缩包中，都没有描述，如何在Windows上安装这个插件。

后知后觉地替换了rime.dll文件。

**Comment by hchunhui** [comment]
小狼毫最新版已经默认编译本项目，不需再额外安装。releases 中的 dll 是供旧版小狼毫使用的。

**Comment by dongyuwei** [comment]
@hchunhui 请问“小狼毫最新版已经默认编译本项目” 这个相关的代码在哪？我看了小狼毫和rime的代码库，没有找到和这个插件相关的地方（编译构建，ci等）。

**Comment by dongyuwei** [comment]
okay, 我找到了， https://github.com/rime/librime/blob/master/.github/workflows/release-ci.yml#L21
看起来是windows和mac版librime都集成了这个插件。但是linux版没有（why？）。
