### ISSUE TITLE
如何调试

### ISSUE THREAD

**Issue by unihon** [hchunhui/librime-lua#43]
如何调试脚本内容，想看日志。

**Comment by hchunhui** [comment]
最新的 commit 已经支持用 `log.info()` `log.warning()` 和 `log.error()` 记日志，不过要等官方 rime 发行版下次发布，或者自己编译才能用。小狼毫用户可以找本项目最新 commit 的 ci 编译，下载`rime.dll`， 覆盖原文件试用。

此前没有专门的调试方案，可以考虑通过写文件、生成候选项等方法输出要调试的内容。

**Comment by unihon** [comment]
谢谢 😀

**Comment by LawssssCat** [comment]
请问现在的weasel（0.14.3）支持 `log` 吗？

我现在在lua_filter中直接调用 `log.info()` 还是会报错 nil

<https://github.com/shewer/librime-lua-script/commit/1b628dc90b650f10b1603904b7b4e3df07a80575#r83601583>

请问要现在22年怎么弄才能使用上 `log` ？

**Comment by shewer** [comment]
> 最新的 commit 已经支持用 `log.info()` `log.warning()` 和 `log.error()` 记日志，不过要等官方 rime 发行版下次发布，或者自己编译才能用。小狼毫用户可以找本项目最新 commit 的 ci 编译，下载`rime.dll`， 覆盖原文件试用。
> 
> 此前没有专门的调试方案，可以考虑通过写文件、生成候选项等方法输出要调试的内容


use croissant   and rime_api_console
luarocks install croissant --local

rime.lua
```lua
GD= require 'croissant.debugger'
GD()  ---    break point

**Comment by hchunhui** [comment]
> 请问现在的weasel（0.14.3）支持 `log` 吗？
> 
> 我现在在lua_filter中直接调用 `log.info()` 还是会报错 nil

log 是比较近加入的功能。 weasel 还没有发布新版本，所以会报 nil。

如需这个功能，要手动将 weasel 安装目录下的 `rime.dll` 手工替换为 github action 里面最新的 artifact。
例如现在最新的build在 https://github.com/hchunhui/librime-lua/actions/runs/3026493926 ，点击这个页面的 artifact 按钮下载。下载以后打开 rime-xxxx-Windows.7z 解压其中的 `dist/lib/rime.dll` 即可。替换时如遇到文件被占用，需先点击 weasel “停止算法服务”，替换后再打开。

**Comment by shewer** [comment]
weasel0.1.4.3  即使2021重編但是 sourc cade是2019的 可能真的沒有bind log

**Comment by LawssssCat** [comment]
> 如需这个功能，要手动将 weasel 安装目录下的 `rime.dll` 手工替换为 github action 里面最新的 artifact。 例如现在最新的build在 https://github.com/hchunhui/librime-lua/actions/runs/3026493926 ，点击这个页面的 artifact 按钮下载。下载以后打开 rime-xxxx-Windows.7z 解压其中的 `dist/lib/rime.dll` 即可。替换时如遇到文件被占用，需先点击 weasel “停止算法服务”，替换后再打开。

感谢，安装成功了。

请问这是这是这个插件的正常安装方法吗？还是只是更新的方法？能否在 README.md 中说下这个插件怎么安装？（不然像我这种看不懂c代码的看的一头懵😂）
