### ISSUE TITLE
如何在送字上屏時 執行外部指令 (ex   http://www.google.com 送字時 將執行 外部指令，且清除text )  

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#51]
如題
該在 processor  translator or filter 中 ?? 感覺應該在processor 內 
用途。  反查 CNS1643 碼, 開啟 WEB 查全字庫
             送字時兼發音
cns-1642  轉碼表 
男女發音檔案mp3 ，檔名以 terry_pinyin 編碼
链接：https://pan.baidu.com/s/1zjH0k5-DeF8tvQfjeJV2sA 
提取码：hzsr

**Comment by hchunhui** [comment]
参考 https://github.com/hchunhui/librime-lua/issues/35#issuecomment-612590327
