### ISSUE TITLE
processKeyevent error 

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#52]
切換反查 DB正常 工作  一應該在 process中有小BUG 

E0721 01:29:24.772047 16536 lua_gears.cc:113] LuaProcessor::ProcessKeyEvent error(2): bad argument #1 to '?' (number expected, got nil)

長的很快 每秒 8條
三個判斷式都可正常工作  , 感覺像 return  KAccepted KNoop 的問題
對processor  return   用義為何??   謝謝
``` lua
local function processor(key,env)   -- 攔截 trig_key  循環切換反查表  index_num  +1 % base
    local kAccepted = 1
    local kNoop=2
    local engine = env.engine
    local context = engine.context

    --  正循環
    if key:repr() ==  trig_nkey then --     循環切換反查字典 0 off  
        index_num=  (index_num +1 ) % base
        context:refresh_non_confirmed_composition()
        return kAccepted
        -- 反循環
    elseif key:repr() == trig_pkey then --
        index_num = (index_num -1 + base) % base
        context:refresh_non_confirmed_composition() -- 刷新 filter data
        return kAccepted
        -- 快碼字串比對  符合才進入修改 index_num
    elseif "number"  == type( pattern[context.input] ) then   -- context.input 可調出 比對 快碼 符合
        index_num =  pattern[context.input]  or index_num     -- 如果 無值  時 不異動 index_num
        context:clear()  -- 清除 contex data
        return kNoop
    end
end

```

**Comment by Ace-Who** [comment]
`index_num` 没有初始化吗？`nil` 不能参与算术运算。

**Comment by hchunhui** [comment]
三个条㭌都不满足时，没有 return 语句。在函数体最后一行前加一条 `return kNoop` 应该就好了

**Comment by hchunhui** [comment]
参考：
https://github.com/rime/home/wiki/RimeWithSchemata#%E7%90%86%E8%A7%A3-processors

> 按鍵消息依次送往列表中的 processor，由他給出對按鍵的處理意見：
>  或曰「收」、即由 Rime 響應該按鍵；
>  或曰「拒」、回禀操作系統 Rime 不做響應、請對按鍵做默認處理；
>  或曰這個按鍵我不認得、請下一個 processor 繼續看。

“收” `kAccepted`、“拒” `kRejected`、“不认得” `kNoop` 分别对应返回值 1、0 和 2。
