### ISSUE TITLE
請問關於上字時 檢查 輸入 text 與 最簡碼 不符檢查 時 beep 一聲

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#53]
目前已完成 顯示最簡碼   想再進一步  ， 如果 上屏時 text 長度 大於  reverse_lookup_filter 最小長度時
發告警聲      
    furction beep()
        print( string.char(07)) 
   end 
我想應該類似在 express_editor 這種程序且放在 processes 最後檢查上屏 keyevent  插入程序 
這樣會不會與 express_editor 衝突 或是 取代

**Comment by hchunhui** [comment]
实现的 processor 总是返回 2（即`kNoop`），并且尽量放在 express_editor 等的前面，这样就应该既不会取代其他processor，按键也不会被它们截获。

另外，我觉得这个 beep 函数应该不会按预期发声，可能要调用外部程序才行。

**Comment by shewer** [comment]
嗯 沒有用   print 沒有送到 stdout
