### ISSUE TITLE
windows librime-lua 可以載入 dll 嗎  另外 可以加入 yaml  & ffi 模組嗎

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#56]
如題  
想要從 schema 取得 preedit_format comment_format

**Comment by hchunhui** [comment]
可以，但对于这个需求没必要。可以从 `env.engine.schema.config` 中得到配置。

**Comment by shewer** [comment]
請問有 範例嗎
我  用 local config= env.engine.schema.config  
  inspect(config)  還是  <userdata 1> 
--- type.cc
static const luaL_Reg vars_get[] = {
    { "schema_id", WRAPMEM(T::schema_id) },
    { "schema_name", WRAPMEM(T::schema_name) },
    { "config", WRAPMEM(T::config) },  // 
    { "page_size", WRAPMEM(T::page_size) },
    { "select_keys", WRAPMEM(T::select_keys) },
    { NULL, NULL },
  };

**Comment by hchunhui** [comment]
大概是这样用：
```lua
local config = env.engine.schema.config
value = config:get_int("foo/bar")
config:set_int("foo/bar", new_value)
```
其中的 `int` 根据类型还可以是 `bool`, `double`, `string` 等。

语法与补丁一样， `/` 表示路径分割；`@n` 表示列表第 n 个元素（从零开始算；`get_list_size()` 可以得到总数）。

**Comment by shewer** [comment]
嗯 試一下 可以存  取 但是 不起作用   initial_quality   反查切換 巳告一段落 先休息一下  ^^

**Comment by shewer** [comment]
今天試 有 存 取  到  
但是   沒有反應   預設 :true    在running 中無法改變現狀   
```lua
--  processor
local reg= "translator/enable_completion"
local config= ENV.engine.schema.config
local completion= config:get_bool(reg)
log.info( "--log initialize --getform ---env translator/enable_completion= " .. tostring(completion ))
config:set_bool(reg, not completion )
```
