### ISSUE TITLE
如果debug呢？

### ISSUE THREAD

**Issue by jimmy54** [hchunhui/librime-lua#6]
自己写的lua如debug是否生成？函数是否执行了。能否有一个教程？

**Comment by hchunhui** [comment]
debug 方面的功能有待完善。

现有 debug 的办法：
1. 看 rime log：lua 函数执行有错时，rime log 中会有错误信息；
2. 在 lua 函数中 print 或写文件。

**Comment by fhfuih** [comment]
> 2. 在 lua 函数中 print 或写文件。

请问print出来的信息会在哪里呢？谢谢

**Comment by shewer** [comment]
用 log.info( string)   log.warning(string) log.error(string)
https://github.com/hchunhui/librime-lua/blob/03a2bd9e172549cb16c0718b2c9b68e8c5678085/src/types.cc#L1343-L1346
windows 
%USER%/APPDATA/local/temp/rime.xxxxxx.....log
linux 
/tmp/rime.xxxxxxx....log
