### ISSUE TITLE
請問 engine.schema.config:set_xxx() 設定後 如何即時生效 

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#61]
如題  如  enabele_completion:     true/false  改完 生效

**Comment by hchunhui** [comment]
config 中的内容是即时生效的，但 config 值背后所代表的功能是否能即时生效，则要看对应组件读取 config 的时机。
因为大部分组件只在 constructor 中读取 config，所以无法做到即时生效。

**Comment by shewer** [comment]
了解  thk
