### ISSUE TITLE
载入不了lua函数，到底咋回事啊

### ISSUE THREAD

**Issue by yetAnotherAssassin** [hchunhui/librime-lua#65]
都是示例里的代码，
`lua_filter@reverse_lookup_filter` 就可以正常运行，
在 rime.lua 里把函数随便改个名字，比如`ddd = require("single_char")`，然后` - lua_filter@reverse_lookup_filter`，就什么都显示不了，
log 一直输出
`E0830 06:56:48.727880 17824 lua_gears.cc:15] LuaTranslation::Next error(2): [string "return function (f, ...)..."]:3: attempt to call a nil value (upvalue 'f')`
这玩意。

Translator 也是一样，把`time_translator = require("time")`改成`tt = require("time")`就啥都没了。

到底咋回事啊？

不会是输入法版本的问题吧？不会吧不会吧？

我的是最新的14.3版啊。

**Comment by hchunhui** [comment]
`lua_filter` 或 `lua_translator` 的 `@` 号后面跟的是 lua 函数的名字。本例中在把函数改名为 `ddd` 和 `tt` 后，对应的配置项应相应改为 `lua_filter@ddd` 和 `lua_filter@tt`。

**Comment by yetAnotherAssassin** [comment]
> `lua_filter` 或 `lua_translator` 的 `@` 号后面跟的是 lua 函数的名字。本例中在把函数改名为 `ddd` 和 `tt` 后，对应的配置项应相应改为 `lua_filter@ddd` 和 `lua_translator@tt`。

改了啊，就是出错。改个名字都能出错我是真的想不明白。

**Comment by yetAnotherAssassin** [comment]
不知道咋回事能用了。
那没事了。
