### ISSUE TITLE
lua插件功能异常，导致rime.dll 无限崩溃

### ISSUE THREAD

**Issue by yanhuacuo** [hchunhui/librime-lua#69]
最新的 commit ：「 https://github.com/hchunhui/librime-lua/commit/5e15032a58828e39237d3da50c88136aff16b660 」

编译不报错的情形下，生成的 rime.dll 无法正常加载，无限崩溃。

https://github.com/hchunhui/librime-lua/blob/5e15032a58828e39237d3da50c88136aff16b660/src/modules.cc#L20

win7 下闪退信息如下：

````
问题签名:


  问题事件名称:	APPCRASH


  应用程序名:	WeaselServer.exe


  应用程序版本:	0.14.3.0


  应用程序时间戳:	5f68e507


  故障模块名称:	rime.dll


  故障模块版本:	0.0.0.0


  故障模块时间戳:	5f68e414


  异常代码:	c0000005


  异常偏移:	00106715


  OS 版本:	6.1.7601.2.1.0.256.1


  区域设置 ID:	2052


  其他信息 1:	0a9e


  其他信息 2:	0a9e372d3b4ad19135b953a78882e789


  其他信息 3:	0a9e


  其他信息 4:	0a9e372d3b4ad19135b953a78882e789


`````

vs2017 中的报错信息：

https://s1.ax1x.com/2020/09/22/wq2MHf.png

https://s1.ax1x.com/2020/09/22/wq2lE8.png

**Comment by hchunhui** [comment]
谢谢！本来以为是一个无害的修改，但实际上漏改了几处。

**Comment by lotem** [comment]
haha. my bad.

**Comment by yanhuacuo** [comment]
> 谢谢！本来以为是一个无害的修改，但实际上漏改了几处。

期待 travis-ci 构建新版本

**Comment by hchunhui** [comment]
这边的 ci 已经过了，说明没什么问题。昨天合并出 bug 前 ci 已经没过，但修改是如此“无害”，我以为是误报没在意。全靠您发现及时。

travis-ci 是 AppImage 版，是昨天在合并之前构建的，已经是 librime-1.6.1，功能上与现在没有任何区别。所以那边暂时不构建了。
