### ISSUE TITLE
添加好对应输入translator的编码 没有对应提示

### ISSUE THREAD

**Issue by nshusr** [hchunhui/librime-lua#7]
添加好对应输入translator的编码 没有对应提示
输入词组时：
ciz¦
- 词组 ~u

如 orq  时
or¦
- 空

期望效果例如
or¦
- [日期] ~q

**Comment by hchunhui** [comment]
问题描述不太清楚，大概是问 `lua_translator` 如何实现编码提示？

`lua_translator` 本身没有编码提示功能，需要自己用 lua 编程实现。

**Comment by nshusr** [comment]
我在orq 添加了输出日期功能
如：
![image](https://user-images.githubusercontent.com/45023042/59652590-f6b02c80-91c0-11e9-81cc-821fb3513d24.png)
我在输入 or时，没有编码提示 我该如何添加
没有提示：
![image](https://user-images.githubusercontent.com/45023042/59652625-0fb8dd80-91c1-11e9-80a5-980696c02f8c.png)
想要的是我输入
or
``` [日期]    ~q```

**Comment by hchunhui** [comment]
需要在脚本中自行实现这个逻辑。

即输入串分别是 `o`、`or`、`orq` 的时候都需要 `yield` 日期的候选项。
所不同的是，在输入串不全时，注释分别为 `~rq` 和 `~q`。

如果你有兴趣，可以把上述逻辑应该可以抽象出来，做成一套 lua 上的库。

**Comment by nshusr** [comment]
感觉有些繁琐，谢谢，我试试
