### ISSUE TITLE
Segmet  tags 要如何設定 

### ISSUE THREAD

**Issue by shewer** [hchunhui/librime-lua#71]
我想要利用  lua_processor   & lua_segmentor  設定  tag ，讓 lua_translator 辨別
可是 tags 好像是 filter在用的  
謝謝

trans
struct Segment {
set<string> tags;
}

static const luaL_Reg vars_get[] = {
    { "tags", WRAPMEM_GET(T::tags) },
 };
typedef Segment T;
  static const luaL_Reg vars_set[] = {
    { "tags", WRAPMEM_SET(T::tags) },
  };
}

**Comment by shewer** [comment]
以下是我測試的程式
但是 lua_translator   找不到  seg:has_tag("english") ，  
lua_translator  在 abc 下是可正常運作
schema   lua_processor  lua_segmentor 都放在 ascii_composer  ascii_segment 前避免 raw 直接上屏
processor  & segment 都以 option "english"  做 判斷處理 



```lua    
 local function segmentor_func(segs ,env) -- segmetation:Segmentation,env_

         local context=env.engine.context
         if  context:get_option("english")  and context:get_option("ascii_mode") then
             local input=segs.input
             local start=segs:get_current_start_position()
             local _end = segs:get_current_end_position()
             local str= input:sub(start,len )
             local len=( (_end - start) < str:len()  and str:len() ) or (_end - start)

             local segment=Segment(start, start + len )
             segment.tags={english=true}
             segs:add_segment(segment)
             return false
         end
         return true
     end
```

**Comment by hchunhui** [comment]
```lua
segment.tags={english=true}
```
试试改成
```lua
segment.tags=Set({"english"})
```
segmentor 和 tag 我自己很久没用，已不清楚是什么回事了，下面的写法是从旧文件中翻出来的，应该是测试过这样写能用。

**Comment by shewer** [comment]
OK  可以設定了    感謝
