### ISSUE TITLE
请问lua如何获取style/Horizontal参数？

### ISSUE THREAD

**Issue by OnchiuLee** [hchunhui/librime-lua#94]
lua如何获取style/Horizontal参数，以便于当候选项文本过长时利用lua更改横竖排显示

**Comment by shewer** [comment]
应该是没办法改
 显示 直 横 不是 librime的負責 ,  上層在初始化時 己調用 api 取得 style/horizontal
   除非 app 有一直再讀取 style/horizontal , 修改 此值才有用

大部分 engine.schema.config 讀取 多於 寫入 
 寫入的資料要 先於 component 初始化前 （請見 librime/src/rime/engine.cc 初始化)
